/* base.h generated by valac 0.34.7, the Vala compiler, do not modify */


#ifndef __LIB_BASE_BASE_H__
#define __LIB_BASE_BASE_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>

G_BEGIN_DECLS


#define AUMBRALES_BASE_TYPE_CIUDAD (aumbrales_base_ciudad_get_type ())
#define AUMBRALES_BASE_CIUDAD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudad))
#define AUMBRALES_BASE_CIUDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudadClass))
#define AUMBRALES_BASE_IS_CIUDAD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_BASE_TYPE_CIUDAD))
#define AUMBRALES_BASE_IS_CIUDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_BASE_TYPE_CIUDAD))
#define AUMBRALES_BASE_CIUDAD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudadClass))

typedef struct _AumbralesBaseCiudad AumbralesBaseCiudad;
typedef struct _AumbralesBaseCiudadClass AumbralesBaseCiudadClass;
typedef struct _AumbralesBaseCiudadPrivate AumbralesBaseCiudadPrivate;

struct _AumbralesBaseCiudad {
	GObject parent_instance;
	AumbralesBaseCiudadPrivate * priv;
};

struct _AumbralesBaseCiudadClass {
	GObjectClass parent_class;
};


GType aumbrales_base_ciudad_get_type (void) G_GNUC_CONST;
AumbralesBaseCiudad* aumbrales_base_ciudad_new (void);
AumbralesBaseCiudad* aumbrales_base_ciudad_construct (GType object_type);
gchar* aumbrales_base_ciudad_to_string (AumbralesBaseCiudad* self);
gint aumbrales_base_ciudad_get_id (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_id (AumbralesBaseCiudad* self, gint value);
const gchar* aumbrales_base_ciudad_get_nombre (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_nombre (AumbralesBaseCiudad* self, const gchar* value);
const gchar* aumbrales_base_ciudad_get_pais (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_pais (AumbralesBaseCiudad* self, const gchar* value);
gint aumbrales_base_ciudad_get_poblacion (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_poblacion (AumbralesBaseCiudad* self, gint value);
gdouble aumbrales_base_ciudad_get_latitud (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_latitud (AumbralesBaseCiudad* self, gdouble value);
gdouble aumbrales_base_ciudad_get_longitud (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_longitud (AumbralesBaseCiudad* self, gdouble value);


G_END_DECLS

#endif
