/* Ciudad.c generated by valac 0.34.7, the Vala compiler
 * generated from Ciudad.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define AUMBRALES_BASE_TYPE_CIUDAD (aumbrales_base_ciudad_get_type ())
#define AUMBRALES_BASE_CIUDAD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudad))
#define AUMBRALES_BASE_CIUDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudadClass))
#define AUMBRALES_BASE_IS_CIUDAD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_BASE_TYPE_CIUDAD))
#define AUMBRALES_BASE_IS_CIUDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_BASE_TYPE_CIUDAD))
#define AUMBRALES_BASE_CIUDAD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudadClass))

typedef struct _AumbralesBaseCiudad AumbralesBaseCiudad;
typedef struct _AumbralesBaseCiudadClass AumbralesBaseCiudadClass;
typedef struct _AumbralesBaseCiudadPrivate AumbralesBaseCiudadPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AumbralesBaseCiudad {
	GObject parent_instance;
	AumbralesBaseCiudadPrivate * priv;
};

struct _AumbralesBaseCiudadClass {
	GObjectClass parent_class;
};

struct _AumbralesBaseCiudadPrivate {
	gint _id;
	gchar* _nombre;
	gchar* _pais;
	gint _poblacion;
	gdouble _latitud;
	gdouble _longitud;
};


static gpointer aumbrales_base_ciudad_parent_class = NULL;

GType aumbrales_base_ciudad_get_type (void) G_GNUC_CONST;
#define AUMBRALES_BASE_CIUDAD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudadPrivate))
enum  {
	AUMBRALES_BASE_CIUDAD_DUMMY_PROPERTY,
	AUMBRALES_BASE_CIUDAD_ID,
	AUMBRALES_BASE_CIUDAD_NOMBRE,
	AUMBRALES_BASE_CIUDAD_PAIS,
	AUMBRALES_BASE_CIUDAD_POBLACION,
	AUMBRALES_BASE_CIUDAD_LATITUD,
	AUMBRALES_BASE_CIUDAD_LONGITUD
};
AumbralesBaseCiudad* aumbrales_base_ciudad_new (void);
AumbralesBaseCiudad* aumbrales_base_ciudad_construct (GType object_type);
gchar* aumbrales_base_ciudad_to_string (AumbralesBaseCiudad* self);
gint aumbrales_base_ciudad_get_id (AumbralesBaseCiudad* self);
gint aumbrales_base_ciudad_get_poblacion (AumbralesBaseCiudad* self);
gdouble aumbrales_base_ciudad_get_latitud (AumbralesBaseCiudad* self);
gdouble aumbrales_base_ciudad_get_longitud (AumbralesBaseCiudad* self);
const gchar* aumbrales_base_ciudad_get_nombre (AumbralesBaseCiudad* self);
const gchar* aumbrales_base_ciudad_get_pais (AumbralesBaseCiudad* self);
void aumbrales_base_ciudad_set_id (AumbralesBaseCiudad* self, gint value);
void aumbrales_base_ciudad_set_nombre (AumbralesBaseCiudad* self, const gchar* value);
void aumbrales_base_ciudad_set_pais (AumbralesBaseCiudad* self, const gchar* value);
void aumbrales_base_ciudad_set_poblacion (AumbralesBaseCiudad* self, gint value);
void aumbrales_base_ciudad_set_latitud (AumbralesBaseCiudad* self, gdouble value);
void aumbrales_base_ciudad_set_longitud (AumbralesBaseCiudad* self, gdouble value);
static void aumbrales_base_ciudad_finalize (GObject* obj);
static void _vala_aumbrales_base_ciudad_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_aumbrales_base_ciudad_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Constructor para una ciudad.
 */
AumbralesBaseCiudad* aumbrales_base_ciudad_construct (GType object_type) {
	AumbralesBaseCiudad * self = NULL;
	self = (AumbralesBaseCiudad*) g_object_new (object_type, NULL);
	return self;
}


AumbralesBaseCiudad* aumbrales_base_ciudad_new (void) {
	return aumbrales_base_ciudad_construct (AUMBRALES_BASE_TYPE_CIUDAD);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


gchar* aumbrales_base_ciudad_to_string (AumbralesBaseCiudad* self) {
	gchar* result = NULL;
	gchar* ids = NULL;
	gint _tmp0_ = 0;
	gchar* _tmp1_ = NULL;
	gchar* ps = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* la = NULL;
	gdouble _tmp4_ = 0.0;
	gchar* _tmp5_ = NULL;
	gchar* lo = NULL;
	gdouble _tmp6_ = 0.0;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_id;
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	ids = _tmp1_;
	_tmp2_ = self->priv->_poblacion;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	ps = _tmp3_;
	_tmp4_ = self->priv->_latitud;
	_tmp5_ = double_to_string (_tmp4_);
	la = _tmp5_;
	_tmp6_ = self->priv->_longitud;
	_tmp7_ = double_to_string (_tmp6_);
	lo = _tmp7_;
	_tmp8_ = self->priv->_nombre;
	_tmp9_ = g_strconcat (ids, _tmp8_, NULL);
	_tmp10_ = _tmp9_;
	_tmp11_ = self->priv->_pais;
	_tmp12_ = g_strconcat (_tmp10_, _tmp11_, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, ps, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, la, NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat (_tmp17_, lo, NULL);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strconcat (_tmp19_, "\n", NULL);
	_tmp21_ = _tmp20_;
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp10_);
	result = _tmp21_;
	_g_free0 (lo);
	_g_free0 (la);
	_g_free0 (ps);
	_g_free0 (ids);
	return result;
}


gint aumbrales_base_ciudad_get_id (AumbralesBaseCiudad* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_id (AumbralesBaseCiudad* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_id = _tmp0_;
	g_object_notify ((GObject *) self, "id");
}


const gchar* aumbrales_base_ciudad_get_nombre (AumbralesBaseCiudad* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_nombre;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_nombre (AumbralesBaseCiudad* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_nombre);
	self->priv->_nombre = _tmp1_;
	g_object_notify ((GObject *) self, "nombre");
}


const gchar* aumbrales_base_ciudad_get_pais (AumbralesBaseCiudad* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_pais;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_pais (AumbralesBaseCiudad* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_pais);
	self->priv->_pais = _tmp1_;
	g_object_notify ((GObject *) self, "pais");
}


gint aumbrales_base_ciudad_get_poblacion (AumbralesBaseCiudad* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_poblacion;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_poblacion (AumbralesBaseCiudad* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_poblacion = _tmp0_;
	g_object_notify ((GObject *) self, "poblacion");
}


gdouble aumbrales_base_ciudad_get_latitud (AumbralesBaseCiudad* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_latitud;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_latitud (AumbralesBaseCiudad* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_latitud = _tmp0_;
	g_object_notify ((GObject *) self, "latitud");
}


gdouble aumbrales_base_ciudad_get_longitud (AumbralesBaseCiudad* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_longitud;
	result = _tmp0_;
	return result;
}


void aumbrales_base_ciudad_set_longitud (AumbralesBaseCiudad* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_longitud = _tmp0_;
	g_object_notify ((GObject *) self, "longitud");
}


static void aumbrales_base_ciudad_class_init (AumbralesBaseCiudadClass * klass) {
	aumbrales_base_ciudad_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AumbralesBaseCiudadPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_aumbrales_base_ciudad_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_aumbrales_base_ciudad_set_property;
	G_OBJECT_CLASS (klass)->finalize = aumbrales_base_ciudad_finalize;
	/**
	 * Regresa y define el id de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Regresa y define el nombre de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_NOMBRE, g_param_spec_string ("nombre", "nombre", "nombre", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Regresa y define el pais de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_PAIS, g_param_spec_string ("pais", "pais", "pais", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Regresa y define la poblacion  de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_POBLACION, g_param_spec_int ("poblacion", "poblacion", "poblacion", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Regresa y define la latitud de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_LATITUD, g_param_spec_double ("latitud", "latitud", "latitud", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Regresa y define el longitud de la ciudad
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), AUMBRALES_BASE_CIUDAD_LONGITUD, g_param_spec_double ("longitud", "longitud", "longitud", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void aumbrales_base_ciudad_instance_init (AumbralesBaseCiudad * self) {
	self->priv = AUMBRALES_BASE_CIUDAD_GET_PRIVATE (self);
}


static void aumbrales_base_ciudad_finalize (GObject* obj) {
	AumbralesBaseCiudad * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudad);
	_g_free0 (self->priv->_nombre);
	_g_free0 (self->priv->_pais);
	G_OBJECT_CLASS (aumbrales_base_ciudad_parent_class)->finalize (obj);
}


GType aumbrales_base_ciudad_get_type (void) {
	static volatile gsize aumbrales_base_ciudad_type_id__volatile = 0;
	if (g_once_init_enter (&aumbrales_base_ciudad_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AumbralesBaseCiudadClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aumbrales_base_ciudad_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AumbralesBaseCiudad), 0, (GInstanceInitFunc) aumbrales_base_ciudad_instance_init, NULL };
		GType aumbrales_base_ciudad_type_id;
		aumbrales_base_ciudad_type_id = g_type_register_static (G_TYPE_OBJECT, "AumbralesBaseCiudad", &g_define_type_info, 0);
		g_once_init_leave (&aumbrales_base_ciudad_type_id__volatile, aumbrales_base_ciudad_type_id);
	}
	return aumbrales_base_ciudad_type_id__volatile;
}


static void _vala_aumbrales_base_ciudad_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AumbralesBaseCiudad * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudad);
	switch (property_id) {
		case AUMBRALES_BASE_CIUDAD_ID:
		g_value_set_int (value, aumbrales_base_ciudad_get_id (self));
		break;
		case AUMBRALES_BASE_CIUDAD_NOMBRE:
		g_value_set_string (value, aumbrales_base_ciudad_get_nombre (self));
		break;
		case AUMBRALES_BASE_CIUDAD_PAIS:
		g_value_set_string (value, aumbrales_base_ciudad_get_pais (self));
		break;
		case AUMBRALES_BASE_CIUDAD_POBLACION:
		g_value_set_int (value, aumbrales_base_ciudad_get_poblacion (self));
		break;
		case AUMBRALES_BASE_CIUDAD_LATITUD:
		g_value_set_double (value, aumbrales_base_ciudad_get_latitud (self));
		break;
		case AUMBRALES_BASE_CIUDAD_LONGITUD:
		g_value_set_double (value, aumbrales_base_ciudad_get_longitud (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_aumbrales_base_ciudad_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AumbralesBaseCiudad * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AUMBRALES_BASE_TYPE_CIUDAD, AumbralesBaseCiudad);
	switch (property_id) {
		case AUMBRALES_BASE_CIUDAD_ID:
		aumbrales_base_ciudad_set_id (self, g_value_get_int (value));
		break;
		case AUMBRALES_BASE_CIUDAD_NOMBRE:
		aumbrales_base_ciudad_set_nombre (self, g_value_get_string (value));
		break;
		case AUMBRALES_BASE_CIUDAD_PAIS:
		aumbrales_base_ciudad_set_pais (self, g_value_get_string (value));
		break;
		case AUMBRALES_BASE_CIUDAD_POBLACION:
		aumbrales_base_ciudad_set_poblacion (self, g_value_get_int (value));
		break;
		case AUMBRALES_BASE_CIUDAD_LATITUD:
		aumbrales_base_ciudad_set_latitud (self, g_value_get_double (value));
		break;
		case AUMBRALES_BASE_CIUDAD_LONGITUD:
		aumbrales_base_ciudad_set_longitud (self, g_value_get_double (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



