/* AUmbrales-main.c generated by valac 0.34.7, the Vala compiler
 * generated from AUmbrales-main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <float.h>
#include <math.h>
#include "aceptacion.h"
#include <stdio.h>
#include <gio/gio.h>


#define AUMBRALES_TYPE_MAIN (aumbrales_main_get_type ())
#define AUMBRALES_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_MAIN, AumbralesMain))
#define AUMBRALES_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_MAIN, AumbralesMainClass))
#define AUMBRALES_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_MAIN))
#define AUMBRALES_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_MAIN))
#define AUMBRALES_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_MAIN, AumbralesMainClass))

typedef struct _AumbralesMain AumbralesMain;
typedef struct _AumbralesMainClass AumbralesMainClass;
typedef struct _AumbralesMainPrivate AumbralesMainPrivate;

#define AUMBRALES_TYPE_MODELO_DB (aumbrales_modelo_db_get_type ())
#define AUMBRALES_MODELO_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDB))
#define AUMBRALES_MODELO_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDBClass))
#define AUMBRALES_IS_MODELO_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_MODELO_DB))
#define AUMBRALES_IS_MODELO_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_MODELO_DB))
#define AUMBRALES_MODELO_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDBClass))

typedef struct _AumbralesModeloDB AumbralesModeloDB;
typedef struct _AumbralesModeloDBClass AumbralesModeloDBClass;

#define AUMBRALES_TYPE_AUMBRALES (aumbrales_aumbrales_get_type ())
#define AUMBRALES_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales))
#define AUMBRALES_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))
#define AUMBRALES_IS_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_IS_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_AUMBRALES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))

typedef struct _AumbralesAumbrales AumbralesAumbrales;
typedef struct _AumbralesAumbralesClass AumbralesAumbralesClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _AumbralesMain {
	GObject parent_instance;
	AumbralesMainPrivate * priv;
};

struct _AumbralesMainClass {
	GObjectClass parent_class;
};


static gpointer aumbrales_main_parent_class = NULL;

GType aumbrales_main_get_type (void) G_GNUC_CONST;
enum  {
	AUMBRALES_MAIN_DUMMY_PROPERTY
};
gint aumbrales_main_main (gchar** args, int args_length1);
GType aumbrales_modelo_db_get_type (void) G_GNUC_CONST;
AumbralesModeloDB* aumbrales_modelo_db_new (void);
AumbralesModeloDB* aumbrales_modelo_db_construct (GType object_type);
GeeHashMap* aumbrales_modelo_db_getConexiones (AumbralesModeloDB* self);
GType aumbrales_aumbrales_get_type (void) G_GNUC_CONST;
AumbralesAumbrales* aumbrales_aumbrales_new (AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp);
AumbralesAumbrales* aumbrales_aumbrales_construct (GType object_type, AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp);
void aumbrales_aumbrales_aceptacionPorUmbrales (AumbralesAumbrales* self, gdouble t, gint* sol, int sol_length1);
gint* aumbrales_aumbrales_get_mejor (AumbralesAumbrales* self, int* result_length1);
AumbralesMain* aumbrales_main_new (void);
AumbralesMain* aumbrales_main_construct (GType object_type);


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
	if (self) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup ("true");
		result = _tmp0_;
		return result;
	} else {
		gchar* _tmp1_ = NULL;
		_tmp1_ = g_strdup ("false");
		result = _tmp1_;
		return result;
	}
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


gint aumbrales_main_main (gchar** args, int args_length1) {
	gint result = 0;
	AumbralesModeloDB* db = NULL;
	AumbralesModeloDB* _tmp0_ = NULL;
	GeeHashMap* h = NULL;
	AumbralesModeloDB* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	AumbralesAceptacionSolucion* s = NULL;
	GeeHashMap* _tmp3_ = NULL;
	AumbralesAceptacionSolucion* _tmp4_ = NULL;
	gint* sini = NULL;
	gint* _tmp5_ = NULL;
	gint sini_length1 = 0;
	gint _sini_size_ = 0;
	AumbralesAceptacionSolucion* _tmp6_ = NULL;
	gint* _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	AumbralesAumbrales* a = NULL;
	AumbralesAceptacionSolucion* _tmp8_ = NULL;
	AumbralesAumbrales* _tmp9_ = NULL;
	AumbralesAumbrales* _tmp10_ = NULL;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	gchar* ou = NULL;
	gchar* _tmp12_ = NULL;
	AumbralesAumbrales* _tmp13_ = NULL;
	gint* _tmp14_ = NULL;
	gint _tmp14__length1 = 0;
	gint* _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	const gchar* _tmp25_ = NULL;
	AumbralesAceptacionSolucion* _tmp26_ = NULL;
	AumbralesAumbrales* _tmp27_ = NULL;
	gint* _tmp28_ = NULL;
	gint _tmp28__length1 = 0;
	gint* _tmp29_ = NULL;
	gint _tmp29__length1 = 0;
	gint _tmp30_ = 0;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	AumbralesAceptacionSolucion* _tmp37_ = NULL;
	AumbralesAumbrales* _tmp38_ = NULL;
	gint* _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	gint* _tmp40_ = NULL;
	gint _tmp40__length1 = 0;
	gboolean _tmp41_ = FALSE;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	AumbralesAceptacionSolucion* _tmp48_ = NULL;
	AumbralesAumbrales* _tmp49_ = NULL;
	gint* _tmp50_ = NULL;
	gint _tmp50__length1 = 0;
	gint* _tmp51_ = NULL;
	gint _tmp51__length1 = 0;
	gdouble _tmp52_ = 0.0;
	gchar* _tmp53_ = NULL;
	gchar* _tmp54_ = NULL;
	gchar* _tmp55_ = NULL;
	gchar* _tmp56_ = NULL;
	gchar* _tmp57_ = NULL;
	FILE* _tmp58_ = NULL;
	AumbralesAceptacionSolucion* _tmp59_ = NULL;
	AumbralesAumbrales* _tmp60_ = NULL;
	gint* _tmp61_ = NULL;
	gint _tmp61__length1 = 0;
	gint* _tmp62_ = NULL;
	gint _tmp62__length1 = 0;
	gint _tmp63_ = 0;
	AumbralesAceptacionSolucion* _tmp64_ = NULL;
	AumbralesAumbrales* _tmp65_ = NULL;
	gint* _tmp66_ = NULL;
	gint _tmp66__length1 = 0;
	gint* _tmp67_ = NULL;
	gint _tmp67__length1 = 0;
	gboolean _tmp68_ = FALSE;
	gchar* _tmp69_ = NULL;
	gchar* _tmp70_ = NULL;
	FILE* _tmp71_ = NULL;
	AumbralesAceptacionSolucion* _tmp72_ = NULL;
	AumbralesAumbrales* _tmp73_ = NULL;
	gint* _tmp74_ = NULL;
	gint _tmp74__length1 = 0;
	gint* _tmp75_ = NULL;
	gint _tmp75__length1 = 0;
	gdouble _tmp76_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = aumbrales_modelo_db_new ();
	db = _tmp0_;
	_tmp1_ = db;
	_tmp2_ = aumbrales_modelo_db_getConexiones (_tmp1_);
	h = _tmp2_;
	_tmp3_ = h;
	_tmp4_ = aumbrales_aceptacion_solucion_new (_tmp3_, 20, 2);
	s = _tmp4_;
	_tmp5_ = g_new0 (gint, 78);
	_tmp5_[0] = 1;
	_tmp5_[1] = 5;
	_tmp5_[2] = 9;
	_tmp5_[3] = 12;
	_tmp5_[4] = 16;
	_tmp5_[5] = 22;
	_tmp5_[6] = 23;
	_tmp5_[7] = 29;
	_tmp5_[8] = 30;
	_tmp5_[9] = 31;
	_tmp5_[10] = 39;
	_tmp5_[11] = 48;
	_tmp5_[12] = 52;
	_tmp5_[13] = 56;
	_tmp5_[14] = 58;
	_tmp5_[15] = 62;
	_tmp5_[16] = 65;
	_tmp5_[17] = 66;
	_tmp5_[18] = 70;
	_tmp5_[19] = 75;
	_tmp5_[20] = 80;
	_tmp5_[21] = 84;
	_tmp5_[22] = 86;
	_tmp5_[23] = 90;
	_tmp5_[24] = 92;
	_tmp5_[25] = 94;
	_tmp5_[26] = 95;
	_tmp5_[27] = 101;
	_tmp5_[28] = 107;
	_tmp5_[29] = 117;
	_tmp5_[30] = 119;
	_tmp5_[31] = 122;
	_tmp5_[32] = 133;
	_tmp5_[33] = 135;
	_tmp5_[34] = 143;
	_tmp5_[35] = 144;
	_tmp5_[36] = 146;
	_tmp5_[37] = 147;
	_tmp5_[38] = 150;
	_tmp5_[39] = 158;
	_tmp5_[40] = 159;
	_tmp5_[41] = 160;
	_tmp5_[42] = 166;
	_tmp5_[43] = 167;
	_tmp5_[44] = 176;
	_tmp5_[45] = 178;
	_tmp5_[46] = 179;
	_tmp5_[47] = 185;
	_tmp5_[48] = 186;
	_tmp5_[49] = 188;
	_tmp5_[50] = 190;
	_tmp5_[51] = 191;
	_tmp5_[52] = 194;
	_tmp5_[53] = 198;
	_tmp5_[54] = 200;
	_tmp5_[55] = 203;
	_tmp5_[56] = 207;
	_tmp5_[57] = 209;
	_tmp5_[58] = 213;
	_tmp5_[59] = 215;
	_tmp5_[60] = 216;
	_tmp5_[61] = 220;
	_tmp5_[62] = 221;
	_tmp5_[63] = 224;
	_tmp5_[64] = 227;
	_tmp5_[65] = 232;
	_tmp5_[66] = 233;
	_tmp5_[67] = 235;
	_tmp5_[68] = 238;
	_tmp5_[69] = 241;
	_tmp5_[70] = 244;
	_tmp5_[71] = 248;
	_tmp5_[72] = 250;
	_tmp5_[73] = 254;
	_tmp5_[74] = 264;
	_tmp5_[75] = 266;
	_tmp5_[76] = 274;
	_tmp5_[77] = 276;
	sini = _tmp5_;
	sini_length1 = 78;
	_sini_size_ = sini_length1;
	_tmp6_ = s;
	_tmp7_ = sini;
	_tmp7__length1 = sini_length1;
	aumbrales_aceptacion_solucion_caminoNoAleatorio (_tmp6_, _tmp7_, _tmp7__length1);
	_tmp8_ = s;
	_tmp9_ = aumbrales_aumbrales_new (_tmp8_, 500, 0.9, 0.001, 0.1);
	a = _tmp9_;
	_tmp10_ = a;
	_tmp11_ = sini;
	_tmp11__length1 = sini_length1;
	aumbrales_aumbrales_aceptacionPorUmbrales (_tmp10_, (gdouble) 4, _tmp11_, _tmp11__length1);
	_tmp12_ = g_strdup ("");
	ou = _tmp12_;
	_tmp13_ = a;
	_tmp14_ = aumbrales_aumbrales_get_mejor (_tmp13_, &_tmp14__length1);
	_tmp15_ = _tmp14_;
	_tmp15__length1 = _tmp14__length1;
	{
		gint* i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp15_;
		i_collection_length1 = _tmp15__length1;
		for (i_it = 0; i_it < _tmp15__length1; i_it = i_it + 1) {
			gint i = 0;
			i = i_collection[i_it];
			{
				const gchar* _tmp16_ = NULL;
				gint _tmp17_ = 0;
				gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				FILE* _tmp23_ = NULL;
				gint _tmp24_ = 0;
				_tmp16_ = ou;
				_tmp17_ = i;
				_tmp18_ = g_strdup_printf ("%i", _tmp17_);
				_tmp19_ = _tmp18_;
				_tmp20_ = g_strconcat (_tmp19_, ",", NULL);
				_tmp21_ = _tmp20_;
				_tmp22_ = g_strconcat (_tmp16_, _tmp21_, NULL);
				_g_free0 (ou);
				ou = _tmp22_;
				_g_free0 (_tmp21_);
				_g_free0 (_tmp19_);
				_tmp23_ = stdout;
				_tmp24_ = i;
				fprintf (_tmp23_, "%d ,", _tmp24_);
			}
		}
	}
	_tmp25_ = ou;
	_tmp26_ = s;
	_tmp27_ = a;
	_tmp28_ = aumbrales_aumbrales_get_mejor (_tmp27_, &_tmp28__length1);
	_tmp29_ = _tmp28_;
	_tmp29__length1 = _tmp28__length1;
	_tmp30_ = aumbrales_aceptacion_solucion_desconexiones (_tmp26_, _tmp29_, _tmp29__length1);
	_tmp31_ = g_strdup_printf ("%i", _tmp30_);
	_tmp32_ = _tmp31_;
	_tmp33_ = g_strconcat ("\n", _tmp32_, NULL);
	_tmp34_ = _tmp33_;
	_tmp35_ = g_strconcat (_tmp34_, "\n", NULL);
	_tmp36_ = _tmp35_;
	_tmp37_ = s;
	_tmp38_ = a;
	_tmp39_ = aumbrales_aumbrales_get_mejor (_tmp38_, &_tmp39__length1);
	_tmp40_ = _tmp39_;
	_tmp40__length1 = _tmp39__length1;
	_tmp41_ = aumbrales_aceptacion_solucion_factible (_tmp37_, _tmp40_, _tmp40__length1);
	_tmp42_ = bool_to_string (_tmp41_);
	_tmp43_ = _tmp42_;
	_tmp44_ = g_strconcat (_tmp36_, _tmp43_, NULL);
	_tmp45_ = _tmp44_;
	_tmp46_ = g_strconcat (_tmp45_, "\n", NULL);
	_tmp47_ = _tmp46_;
	_tmp48_ = s;
	_tmp49_ = a;
	_tmp50_ = aumbrales_aumbrales_get_mejor (_tmp49_, &_tmp50__length1);
	_tmp51_ = _tmp50_;
	_tmp51__length1 = _tmp50__length1;
	_tmp52_ = aumbrales_aceptacion_solucion_fcosto (_tmp48_, _tmp51_, _tmp51__length1);
	_tmp53_ = double_to_string (_tmp52_);
	_tmp54_ = _tmp53_;
	_tmp55_ = g_strconcat (_tmp47_, _tmp54_, NULL);
	_tmp56_ = _tmp55_;
	_tmp57_ = g_strconcat (_tmp25_, _tmp56_, NULL);
	_g_free0 (ou);
	ou = _tmp57_;
	_g_free0 (_tmp56_);
	_g_free0 (_tmp54_);
	_g_free0 (_tmp47_);
	_g_free0 (_tmp45_);
	_g_free0 (_tmp43_);
	_g_free0 (_tmp36_);
	_g_free0 (_tmp34_);
	_g_free0 (_tmp32_);
	_tmp58_ = stdout;
	_tmp59_ = s;
	_tmp60_ = a;
	_tmp61_ = aumbrales_aumbrales_get_mejor (_tmp60_, &_tmp61__length1);
	_tmp62_ = _tmp61_;
	_tmp62__length1 = _tmp61__length1;
	_tmp63_ = aumbrales_aceptacion_solucion_desconexiones (_tmp59_, _tmp62_, _tmp62__length1);
	_tmp64_ = s;
	_tmp65_ = a;
	_tmp66_ = aumbrales_aumbrales_get_mejor (_tmp65_, &_tmp66__length1);
	_tmp67_ = _tmp66_;
	_tmp67__length1 = _tmp66__length1;
	_tmp68_ = aumbrales_aceptacion_solucion_factible (_tmp64_, _tmp67_, _tmp67__length1);
	_tmp69_ = bool_to_string (_tmp68_);
	_tmp70_ = _tmp69_;
	fprintf (_tmp58_, "desconexiones = %d , f =%s\n", _tmp63_, _tmp70_);
	_g_free0 (_tmp70_);
	_tmp71_ = stdout;
	_tmp72_ = s;
	_tmp73_ = a;
	_tmp74_ = aumbrales_aumbrales_get_mejor (_tmp73_, &_tmp74__length1);
	_tmp75_ = _tmp74_;
	_tmp75__length1 = _tmp74__length1;
	_tmp76_ = aumbrales_aceptacion_solucion_fcosto (_tmp72_, _tmp75_, _tmp75__length1);
	fprintf (_tmp71_, "fcosto=%2.9f\n", _tmp76_);
	{
		GFile* file = NULL;
		gchar* _tmp77_ = NULL;
		gchar* _tmp78_ = NULL;
		gchar* _tmp79_ = NULL;
		gchar* _tmp80_ = NULL;
		gchar* _tmp81_ = NULL;
		gchar* _tmp82_ = NULL;
		gchar* _tmp83_ = NULL;
		gchar* _tmp84_ = NULL;
		GFile* _tmp85_ = NULL;
		GFile* _tmp86_ = NULL;
		GFile* _tmp87_ = NULL;
		gboolean _tmp88_ = FALSE;
		GFileOutputStream* _tmp90_ = NULL;
		GFile* _tmp91_ = NULL;
		GFileOutputStream* _tmp92_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp93_ = NULL;
		GDataOutputStream* _tmp94_ = NULL;
		const gchar* _tmp95_ = NULL;
		_tmp77_ = g_strdup_printf ("%i", 20);
		_tmp78_ = _tmp77_;
		_tmp79_ = g_strconcat ("experimentos/", _tmp78_, NULL);
		_tmp80_ = _tmp79_;
		_tmp81_ = g_strconcat (_tmp80_, "cc2", NULL);
		_tmp82_ = _tmp81_;
		_tmp83_ = g_strconcat (_tmp82_, ".tsp", NULL);
		_tmp84_ = _tmp83_;
		_tmp85_ = g_file_new_for_path (_tmp84_);
		_tmp86_ = _tmp85_;
		_g_free0 (_tmp84_);
		_g_free0 (_tmp82_);
		_g_free0 (_tmp80_);
		_g_free0 (_tmp78_);
		file = _tmp86_;
		_tmp87_ = file;
		_tmp88_ = g_file_query_exists (_tmp87_, NULL);
		if (_tmp88_) {
			GFile* _tmp89_ = NULL;
			_tmp89_ = file;
			g_file_delete (_tmp89_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (file);
				goto __catch0_g_error;
			}
		}
		_tmp91_ = file;
		_tmp92_ = g_file_create (_tmp91_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
		_tmp90_ = _tmp92_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_tmp93_ = g_data_output_stream_new ((GOutputStream*) _tmp90_);
		dos = _tmp93_;
		_tmp94_ = dos;
		_tmp95_ = ou;
		g_data_output_stream_put_string (_tmp94_, _tmp95_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp90_);
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_g_object_unref0 (dos);
		_g_object_unref0 (_tmp90_);
		_g_object_unref0 (file);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp96_ = NULL;
		GError* _tmp97_ = NULL;
		const gchar* _tmp98_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp96_ = stderr;
		_tmp97_ = e;
		_tmp98_ = _tmp97_->message;
		fprintf (_tmp96_, "%s\n", _tmp98_);
		result = 1;
		_g_error_free0 (e);
		_g_free0 (ou);
		_g_object_unref0 (a);
		sini = (g_free (sini), NULL);
		_g_object_unref0 (s);
		_g_object_unref0 (h);
		_g_object_unref0 (db);
		return result;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		gint _tmp99_ = 0;
		_g_free0 (ou);
		_g_object_unref0 (a);
		sini = (g_free (sini), NULL);
		_g_object_unref0 (s);
		_g_object_unref0 (h);
		_g_object_unref0 (db);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp99_;
	}
	result = 0;
	_g_free0 (ou);
	_g_object_unref0 (a);
	sini = (g_free (sini), NULL);
	_g_object_unref0 (s);
	_g_object_unref0 (h);
	_g_object_unref0 (db);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return aumbrales_main_main (argv, argc);
}


AumbralesMain* aumbrales_main_construct (GType object_type) {
	AumbralesMain * self = NULL;
	self = (AumbralesMain*) g_object_new (object_type, NULL);
	return self;
}


AumbralesMain* aumbrales_main_new (void) {
	return aumbrales_main_construct (AUMBRALES_TYPE_MAIN);
}


static void aumbrales_main_class_init (AumbralesMainClass * klass) {
	aumbrales_main_parent_class = g_type_class_peek_parent (klass);
}


static void aumbrales_main_instance_init (AumbralesMain * self) {
}


GType aumbrales_main_get_type (void) {
	static volatile gsize aumbrales_main_type_id__volatile = 0;
	if (g_once_init_enter (&aumbrales_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AumbralesMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aumbrales_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AumbralesMain), 0, (GInstanceInitFunc) aumbrales_main_instance_init, NULL };
		GType aumbrales_main_type_id;
		aumbrales_main_type_id = g_type_register_static (G_TYPE_OBJECT, "AumbralesMain", &g_define_type_info, 0);
		g_once_init_leave (&aumbrales_main_type_id__volatile, aumbrales_main_type_id);
	}
	return aumbrales_main_type_id__volatile;
}



