/* AUmbrales-main.c generated by valac 0.34.7, the Vala compiler
 * generated from AUmbrales-main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "base.h"
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include <stdio.h>
#include "aceptacion.h"


#define AUMBRALES_TYPE_MAIN (aumbrales_main_get_type ())
#define AUMBRALES_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_MAIN, AumbralesMain))
#define AUMBRALES_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_MAIN, AumbralesMainClass))
#define AUMBRALES_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_MAIN))
#define AUMBRALES_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_MAIN))
#define AUMBRALES_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_MAIN, AumbralesMainClass))

typedef struct _AumbralesMain AumbralesMain;
typedef struct _AumbralesMainClass AumbralesMainClass;
typedef struct _AumbralesMainPrivate AumbralesMainPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define AUMBRALES_TYPE_MODELO_DB (aumbrales_modelo_db_get_type ())
#define AUMBRALES_MODELO_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDB))
#define AUMBRALES_MODELO_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDBClass))
#define AUMBRALES_IS_MODELO_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_MODELO_DB))
#define AUMBRALES_IS_MODELO_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_MODELO_DB))
#define AUMBRALES_MODELO_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_MODELO_DB, AumbralesModeloDBClass))

typedef struct _AumbralesModeloDB AumbralesModeloDB;
typedef struct _AumbralesModeloDBClass AumbralesModeloDBClass;

#define AUMBRALES_TYPE_AUMBRALES (aumbrales_aumbrales_get_type ())
#define AUMBRALES_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales))
#define AUMBRALES_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))
#define AUMBRALES_IS_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_IS_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_AUMBRALES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))

typedef struct _AumbralesAumbrales AumbralesAumbrales;
typedef struct _AumbralesAumbralesClass AumbralesAumbralesClass;

struct _AumbralesMain {
	GObject parent_instance;
	AumbralesMainPrivate * priv;
};

struct _AumbralesMainClass {
	GObjectClass parent_class;
};


static gpointer aumbrales_main_parent_class = NULL;

GType aumbrales_main_get_type (void) G_GNUC_CONST;
enum  {
	AUMBRALES_MAIN_DUMMY_PROPERTY
};
void aumbrales_main_graficaMapa (AumbralesBaseCiudad** c, int c_length1, gint* sol, int sol_length1, gint seed);
static gchar* aumbrales_main_creaCirculo (gdouble x, gdouble y);
static gchar* aumbrales_main_linea (gdouble x, gdouble y, gdouble v, gdouble w);
gchar** aumbrales_main_archivo (const gchar* arc, int* result_length1);
gint aumbrales_main_main (gchar** args, int args_length1);
GType aumbrales_modelo_db_get_type (void) G_GNUC_CONST;
AumbralesModeloDB* aumbrales_modelo_db_new (void);
AumbralesModeloDB* aumbrales_modelo_db_construct (GType object_type);
gdouble* aumbrales_modelo_db_getConexiones (AumbralesModeloDB* self, int* result_length1, int* result_length2);
GType aumbrales_aumbrales_get_type (void) G_GNUC_CONST;
AumbralesAumbrales* aumbrales_aumbrales_new (AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name);
AumbralesAumbrales* aumbrales_aumbrales_construct (GType object_type, AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name);
void aumbrales_aumbrales_aceptacionPorUmbrales (AumbralesAumbrales* self, gdouble t, gint* sol, int sol_length1);
gint* aumbrales_aumbrales_get_mejor (AumbralesAumbrales* self, int* result_length1);
AumbralesBaseCiudad** aumbrales_modelo_db_getCiudades (AumbralesModeloDB* self, int* result_length1);
AumbralesMain* aumbrales_main_new (void);
AumbralesMain* aumbrales_main_construct (GType object_type);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


/**
 *Dibuja la solucion en un svg 
 **/
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void aumbrales_main_graficaMapa (AumbralesBaseCiudad** c, int c_length1, gint* sol, int sol_length1, gint seed) {
	gint w = 0;
	gint h = 0;
	gchar* s = NULL;
	gint _tmp0_ = 0;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	const gchar* _tmp82_ = NULL;
	gchar* _tmp83_ = NULL;
	GError * _inner_error_ = NULL;
	w = 3500;
	h = 1500;
	_tmp0_ = w;
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" "<svg width=\"", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, "\" height=\"", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = h;
	_tmp8_ = g_strdup_printf ("%i", _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp6_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, "\">\n", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "<g>\n", NULL);
	_tmp15_ = _tmp14_;
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	s = _tmp15_;
	_tmp16_ = s;
	_tmp17_ = w;
	_tmp18_ = g_strdup_printf ("%i", _tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strconcat ("<rect width='", _tmp19_, NULL);
	_tmp21_ = _tmp20_;
	_tmp22_ = g_strconcat (_tmp21_, "' height='", NULL);
	_tmp23_ = _tmp22_;
	_tmp24_ = h;
	_tmp25_ = g_strdup_printf ("%i", _tmp24_);
	_tmp26_ = _tmp25_;
	_tmp27_ = g_strconcat (_tmp23_, _tmp26_, NULL);
	_tmp28_ = _tmp27_;
	_tmp29_ = g_strconcat (_tmp28_, "' fill='black'/>\n", NULL);
	_tmp30_ = _tmp29_;
	_tmp31_ = g_strconcat (_tmp16_, _tmp30_, NULL);
	_g_free0 (s);
	s = _tmp31_;
	_g_free0 (_tmp30_);
	_g_free0 (_tmp28_);
	_g_free0 (_tmp26_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp19_);
	{
		gint i = 0;
		i = 1;
		{
			gboolean _tmp32_ = FALSE;
			_tmp32_ = TRUE;
			while (TRUE) {
				gint _tmp34_ = 0;
				AumbralesBaseCiudad** _tmp35_ = NULL;
				gint _tmp35__length1 = 0;
				const gchar* _tmp36_ = NULL;
				AumbralesBaseCiudad** _tmp37_ = NULL;
				gint _tmp37__length1 = 0;
				gint _tmp38_ = 0;
				AumbralesBaseCiudad* _tmp39_ = NULL;
				gdouble _tmp40_ = 0.0;
				gdouble _tmp41_ = 0.0;
				AumbralesBaseCiudad** _tmp42_ = NULL;
				gint _tmp42__length1 = 0;
				gint _tmp43_ = 0;
				AumbralesBaseCiudad* _tmp44_ = NULL;
				gdouble _tmp45_ = 0.0;
				gdouble _tmp46_ = 0.0;
				gchar* _tmp47_ = NULL;
				gchar* _tmp48_ = NULL;
				gchar* _tmp49_ = NULL;
				if (!_tmp32_) {
					gint _tmp33_ = 0;
					_tmp33_ = i;
					i = _tmp33_ + 1;
				}
				_tmp32_ = FALSE;
				_tmp34_ = i;
				_tmp35_ = c;
				_tmp35__length1 = c_length1;
				if (!(_tmp34_ < _tmp35__length1)) {
					break;
				}
				_tmp36_ = s;
				_tmp37_ = c;
				_tmp37__length1 = c_length1;
				_tmp38_ = i;
				_tmp39_ = _tmp37_[_tmp38_];
				_tmp40_ = aumbrales_base_ciudad_get_longitud (_tmp39_);
				_tmp41_ = _tmp40_;
				_tmp42_ = c;
				_tmp42__length1 = c_length1;
				_tmp43_ = i;
				_tmp44_ = _tmp42_[_tmp43_];
				_tmp45_ = aumbrales_base_ciudad_get_latitud (_tmp44_);
				_tmp46_ = _tmp45_;
				_tmp47_ = aumbrales_main_creaCirculo (13.0 * (_tmp41_ + 125.0), 13.0 * (70.0 - _tmp46_));
				_tmp48_ = _tmp47_;
				_tmp49_ = g_strconcat (_tmp36_, _tmp48_, NULL);
				_g_free0 (s);
				s = _tmp49_;
				_g_free0 (_tmp48_);
			}
		}
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp50_ = FALSE;
			_tmp50_ = TRUE;
			while (TRUE) {
				gint _tmp52_ = 0;
				gint* _tmp53_ = NULL;
				gint _tmp53__length1 = 0;
				AumbralesBaseCiudad* c1 = NULL;
				AumbralesBaseCiudad** _tmp54_ = NULL;
				gint _tmp54__length1 = 0;
				gint* _tmp55_ = NULL;
				gint _tmp55__length1 = 0;
				gint _tmp56_ = 0;
				gint _tmp57_ = 0;
				AumbralesBaseCiudad* _tmp58_ = NULL;
				AumbralesBaseCiudad* _tmp59_ = NULL;
				AumbralesBaseCiudad* c2 = NULL;
				AumbralesBaseCiudad** _tmp60_ = NULL;
				gint _tmp60__length1 = 0;
				gint* _tmp61_ = NULL;
				gint _tmp61__length1 = 0;
				gint _tmp62_ = 0;
				gint _tmp63_ = 0;
				AumbralesBaseCiudad* _tmp64_ = NULL;
				AumbralesBaseCiudad* _tmp65_ = NULL;
				const gchar* _tmp66_ = NULL;
				AumbralesBaseCiudad* _tmp67_ = NULL;
				gdouble _tmp68_ = 0.0;
				gdouble _tmp69_ = 0.0;
				AumbralesBaseCiudad* _tmp70_ = NULL;
				gdouble _tmp71_ = 0.0;
				gdouble _tmp72_ = 0.0;
				AumbralesBaseCiudad* _tmp73_ = NULL;
				gdouble _tmp74_ = 0.0;
				gdouble _tmp75_ = 0.0;
				AumbralesBaseCiudad* _tmp76_ = NULL;
				gdouble _tmp77_ = 0.0;
				gdouble _tmp78_ = 0.0;
				gchar* _tmp79_ = NULL;
				gchar* _tmp80_ = NULL;
				gchar* _tmp81_ = NULL;
				if (!_tmp50_) {
					gint _tmp51_ = 0;
					_tmp51_ = i;
					i = _tmp51_ + 1;
				}
				_tmp50_ = FALSE;
				_tmp52_ = i;
				_tmp53_ = sol;
				_tmp53__length1 = sol_length1;
				if (!(_tmp52_ < (_tmp53__length1 - 1))) {
					break;
				}
				_tmp54_ = c;
				_tmp54__length1 = c_length1;
				_tmp55_ = sol;
				_tmp55__length1 = sol_length1;
				_tmp56_ = i;
				_tmp57_ = _tmp55_[_tmp56_];
				_tmp58_ = _tmp54_[_tmp57_];
				_tmp59_ = _g_object_ref0 (_tmp58_);
				c1 = _tmp59_;
				_tmp60_ = c;
				_tmp60__length1 = c_length1;
				_tmp61_ = sol;
				_tmp61__length1 = sol_length1;
				_tmp62_ = i;
				_tmp63_ = _tmp61_[_tmp62_ + 1];
				_tmp64_ = _tmp60_[_tmp63_];
				_tmp65_ = _g_object_ref0 (_tmp64_);
				c2 = _tmp65_;
				_tmp66_ = s;
				_tmp67_ = c1;
				_tmp68_ = aumbrales_base_ciudad_get_longitud (_tmp67_);
				_tmp69_ = _tmp68_;
				_tmp70_ = c1;
				_tmp71_ = aumbrales_base_ciudad_get_latitud (_tmp70_);
				_tmp72_ = _tmp71_;
				_tmp73_ = c2;
				_tmp74_ = aumbrales_base_ciudad_get_longitud (_tmp73_);
				_tmp75_ = _tmp74_;
				_tmp76_ = c2;
				_tmp77_ = aumbrales_base_ciudad_get_latitud (_tmp76_);
				_tmp78_ = _tmp77_;
				_tmp79_ = aumbrales_main_linea (13.0 * (_tmp69_ + 125.0), 13.0 * (70.0 - _tmp72_), 13.0 * (_tmp75_ + 125.0), 13.0 * (70.0 - _tmp78_));
				_tmp80_ = _tmp79_;
				_tmp81_ = g_strconcat (_tmp66_, _tmp80_, NULL);
				_g_free0 (s);
				s = _tmp81_;
				_g_free0 (_tmp80_);
				_g_object_unref0 (c2);
				_g_object_unref0 (c1);
			}
		}
	}
	_tmp82_ = s;
	_tmp83_ = g_strconcat (_tmp82_, "</g>" "</svg>", NULL);
	_g_free0 (s);
	s = _tmp83_;
	{
		GFile* file = NULL;
		gint _tmp84_ = 0;
		gchar* _tmp85_ = NULL;
		gchar* _tmp86_ = NULL;
		gchar* _tmp87_ = NULL;
		gchar* _tmp88_ = NULL;
		gchar* _tmp89_ = NULL;
		gchar* _tmp90_ = NULL;
		GFile* _tmp91_ = NULL;
		GFile* _tmp92_ = NULL;
		GFile* _tmp93_ = NULL;
		gboolean _tmp94_ = FALSE;
		GFileOutputStream* _tmp96_ = NULL;
		GFile* _tmp97_ = NULL;
		GFileOutputStream* _tmp98_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp99_ = NULL;
		GDataOutputStream* _tmp100_ = NULL;
		const gchar* _tmp101_ = NULL;
		_tmp84_ = seed;
		_tmp85_ = g_strdup_printf ("%i", _tmp84_);
		_tmp86_ = _tmp85_;
		_tmp87_ = g_strconcat ("experimentos/svg", _tmp86_, NULL);
		_tmp88_ = _tmp87_;
		_tmp89_ = g_strconcat (_tmp88_, ".svg", NULL);
		_tmp90_ = _tmp89_;
		_tmp91_ = g_file_new_for_path (_tmp90_);
		_tmp92_ = _tmp91_;
		_g_free0 (_tmp90_);
		_g_free0 (_tmp88_);
		_g_free0 (_tmp86_);
		file = _tmp92_;
		_tmp93_ = file;
		_tmp94_ = g_file_query_exists (_tmp93_, NULL);
		if (_tmp94_) {
			GFile* _tmp95_ = NULL;
			_tmp95_ = file;
			g_file_delete (_tmp95_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (file);
				goto __catch0_g_error;
			}
		}
		_tmp97_ = file;
		_tmp98_ = g_file_create (_tmp97_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
		_tmp96_ = _tmp98_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_tmp99_ = g_data_output_stream_new ((GOutputStream*) _tmp96_);
		dos = _tmp99_;
		_tmp100_ = dos;
		_tmp101_ = s;
		g_data_output_stream_put_string (_tmp100_, _tmp101_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp96_);
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_g_object_unref0 (dos);
		_g_object_unref0 (_tmp96_);
		_g_object_unref0 (file);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp102_ = NULL;
		GError* _tmp103_ = NULL;
		const gchar* _tmp104_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp102_ = stderr;
		_tmp103_ = e;
		_tmp104_ = _tmp103_->message;
		fprintf (_tmp102_, "%s\n", _tmp104_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (s);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (s);
}


/**
 *Dubuja linea
 */
static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


static gchar* aumbrales_main_linea (gdouble x, gdouble y, gdouble v, gdouble w) {
	gchar* result = NULL;
	gdouble _tmp0_ = 0.0;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gdouble _tmp7_ = 0.0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gdouble _tmp14_ = 0.0;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gdouble _tmp21_ = 0.0;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	_tmp0_ = x;
	_tmp1_ = double_to_string (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("<line x1='", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, "' y1='", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = y;
	_tmp8_ = double_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp6_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, "' x2='", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = v;
	_tmp15_ = double_to_string (_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp13_, _tmp16_, NULL);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp18_, "' y2='", NULL);
	_tmp20_ = _tmp19_;
	_tmp21_ = w;
	_tmp22_ = double_to_string (_tmp21_);
	_tmp23_ = _tmp22_;
	_tmp24_ = g_strconcat (_tmp20_, _tmp23_, NULL);
	_tmp25_ = _tmp24_;
	_tmp26_ = g_strconcat (_tmp25_, "' style='stroke:rgb(239,1,255);stroke-width:1'/>\n", NULL);
	_tmp27_ = _tmp26_;
	_g_free0 (_tmp25_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp20_);
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	result = _tmp27_;
	return result;
}


/**
 * Dibuja un circulo
 */
static gchar* aumbrales_main_creaCirculo (gdouble x, gdouble y) {
	gchar* result = NULL;
	gdouble _tmp0_ = 0.0;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gdouble _tmp7_ = 0.0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	_tmp0_ = x;
	_tmp1_ = double_to_string (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("<circle cx='", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, "' cy='", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = y;
	_tmp8_ = double_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp6_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, "' r='3' stroke='red' stroke-width='1' fill='black' />\n", NULL);
	_tmp13_ = _tmp12_;
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	result = _tmp13_;
	return result;
}


/**
 * recibe el nombre de el archivo donde esta la entrada del programa
 */
gchar** aumbrales_main_archivo (const gchar* arc, int* result_length1) {
	gchar** result = NULL;
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	gchar** s = NULL;
	gchar** _tmp2_ = NULL;
	gint s_length1 = 0;
	gint _s_size_ = 0;
	GFile* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (arc != NULL, NULL);
	_tmp0_ = arc;
	_tmp1_ = g_file_new_for_path (_tmp0_);
	file = _tmp1_;
	_tmp2_ = g_new0 (gchar*, 0 + 1);
	s = _tmp2_;
	s_length1 = 0;
	_s_size_ = s_length1;
	_tmp3_ = file;
	_tmp4_ = g_file_query_exists (_tmp3_, NULL);
	if (!_tmp4_) {
		FILE* _tmp5_ = NULL;
		GFile* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		_tmp5_ = stderr;
		_tmp6_ = file;
		_tmp7_ = g_file_get_path (_tmp6_);
		_tmp8_ = _tmp7_;
		fprintf (_tmp5_, "File '%s' doesn't exist.\n", _tmp8_);
		_g_free0 (_tmp8_);
	}
	{
		GFileInputStream* _tmp9_ = NULL;
		GFile* _tmp10_ = NULL;
		GFileInputStream* _tmp11_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp12_ = NULL;
		gchar* line = NULL;
		_tmp10_ = file;
		_tmp11_ = g_file_read (_tmp10_, NULL, &_inner_error_);
		_tmp9_ = _tmp11_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch1_g_error;
		}
		_tmp12_ = g_data_input_stream_new ((GInputStream*) _tmp9_);
		dis = _tmp12_;
		while (TRUE) {
			gchar* _tmp13_ = NULL;
			GDataInputStream* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			gchar** _tmp19_ = NULL;
			gchar** _tmp20_ = NULL;
			_tmp14_ = dis;
			_tmp15_ = g_data_input_stream_read_line (_tmp14_, NULL, NULL, &_inner_error_);
			_tmp13_ = _tmp15_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_free0 (line);
				_g_object_unref0 (dis);
				_g_object_unref0 (_tmp9_);
				goto __catch1_g_error;
			}
			_tmp16_ = _tmp13_;
			_tmp13_ = NULL;
			_g_free0 (line);
			line = _tmp16_;
			_tmp17_ = line;
			if (!(_tmp17_ != NULL)) {
				_g_free0 (_tmp13_);
				break;
			}
			_tmp18_ = line;
			_tmp20_ = _tmp19_ = g_strsplit (_tmp18_, ",", 0);
			s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
			s = _tmp20_;
			s_length1 = _vala_array_length (_tmp19_);
			_s_size_ = s_length1;
			_g_free0 (_tmp13_);
		}
		_g_free0 (line);
		_g_object_unref0 (dis);
		_g_object_unref0 (_tmp9_);
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp21_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp21_ = e->message;
		g_error ("AUmbrales-main.vala:79: %s", _tmp21_);
		_g_error_free0 (e);
	}
	__finally1:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp22_ = s;
	_tmp22__length1 = s_length1;
	if (result_length1) {
		*result_length1 = _tmp22__length1;
	}
	result = _tmp22_;
	_g_object_unref0 (file);
	return result;
}


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
	if (self) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup ("true");
		result = _tmp0_;
		return result;
	} else {
		gchar* _tmp1_ = NULL;
		_tmp1_ = g_strdup ("false");
		result = _tmp1_;
		return result;
	}
}


gint aumbrales_main_main (gchar** args, int args_length1) {
	gint result = 0;
	gint seed = 0;
	gint* sol = NULL;
	gint* _tmp0_ = NULL;
	gint sol_length1 = 0;
	gint _sol_size_ = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	AumbralesModeloDB* db = NULL;
	AumbralesModeloDB* _tmp22_ = NULL;
	gdouble* h = NULL;
	AumbralesModeloDB* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	gdouble* _tmp26_ = NULL;
	gint h_length1 = 0;
	gint h_length2 = 0;
	AumbralesAceptacionSolucion* s = NULL;
	gdouble* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	gint _tmp27__length2 = 0;
	gint _tmp28_ = 0;
	AumbralesAceptacionSolucion* _tmp29_ = NULL;
	AumbralesAceptacionSolucion* _tmp30_ = NULL;
	gint* _tmp31_ = NULL;
	gint _tmp31__length1 = 0;
	AumbralesAumbrales* a = NULL;
	AumbralesAceptacionSolucion* _tmp32_ = NULL;
	gint _tmp33_ = 0;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	AumbralesAumbrales* _tmp36_ = NULL;
	AumbralesAumbrales* _tmp37_ = NULL;
	AumbralesAumbrales* _tmp38_ = NULL;
	gint* _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	AumbralesAumbrales* _tmp40_ = NULL;
	gint* _tmp41_ = NULL;
	gint _tmp41__length1 = 0;
	gint* _tmp42_ = NULL;
	gint _tmp42__length1 = 0;
	FILE* _tmp45_ = NULL;
	FILE* _tmp46_ = NULL;
	AumbralesAceptacionSolucion* _tmp47_ = NULL;
	AumbralesAumbrales* _tmp48_ = NULL;
	gint* _tmp49_ = NULL;
	gint _tmp49__length1 = 0;
	gint* _tmp50_ = NULL;
	gint _tmp50__length1 = 0;
	gdouble _tmp51_ = 0.0;
	FILE* _tmp52_ = NULL;
	AumbralesAceptacionSolucion* _tmp53_ = NULL;
	AumbralesAumbrales* _tmp54_ = NULL;
	gint* _tmp55_ = NULL;
	gint _tmp55__length1 = 0;
	gint* _tmp56_ = NULL;
	gint _tmp56__length1 = 0;
	gboolean _tmp57_ = FALSE;
	gchar* _tmp58_ = NULL;
	gchar* _tmp59_ = NULL;
	AumbralesBaseCiudad** l = NULL;
	AumbralesModeloDB* _tmp60_ = NULL;
	gint _tmp61_ = 0;
	AumbralesBaseCiudad** _tmp62_ = NULL;
	gint l_length1 = 0;
	gint _l_size_ = 0;
	AumbralesBaseCiudad** _tmp63_ = NULL;
	gint _tmp63__length1 = 0;
	AumbralesAumbrales* _tmp64_ = NULL;
	gint* _tmp65_ = NULL;
	gint _tmp65__length1 = 0;
	gint* _tmp66_ = NULL;
	gint _tmp66__length1 = 0;
	gint _tmp67_ = 0;
	seed = 0;
	_tmp0_ = g_new0 (gint, 0);
	sol = _tmp0_;
	sol_length1 = 0;
	_sol_size_ = sol_length1;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	if (_tmp1__length1 == 3) {
		gchar** _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		const gchar* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gchar** ent = NULL;
		gchar** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		const gchar* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		gchar** _tmp8_ = NULL;
		gint ent_length1 = 0;
		gint _ent_size_ = 0;
		gchar** _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gint* _tmp10_ = NULL;
		_tmp2_ = args;
		_tmp2__length1 = args_length1;
		_tmp3_ = _tmp2_[1];
		_tmp4_ = atoi (_tmp3_);
		seed = _tmp4_;
		_tmp5_ = args;
		_tmp5__length1 = args_length1;
		_tmp6_ = _tmp5_[2];
		_tmp8_ = aumbrales_main_archivo (_tmp6_, &_tmp7_);
		ent = _tmp8_;
		ent_length1 = _tmp7_;
		_ent_size_ = ent_length1;
		_tmp9_ = ent;
		_tmp9__length1 = ent_length1;
		_tmp10_ = g_new0 (gint, _tmp9__length1);
		sol = (g_free (sol), NULL);
		sol = _tmp10_;
		sol_length1 = _tmp9__length1;
		_sol_size_ = sol_length1;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp11_ = FALSE;
				_tmp11_ = TRUE;
				while (TRUE) {
					gint _tmp13_ = 0;
					gchar** _tmp14_ = NULL;
					gint _tmp14__length1 = 0;
					gint* _tmp15_ = NULL;
					gint _tmp15__length1 = 0;
					gint _tmp16_ = 0;
					gchar** _tmp17_ = NULL;
					gint _tmp17__length1 = 0;
					gint _tmp18_ = 0;
					const gchar* _tmp19_ = NULL;
					gint _tmp20_ = 0;
					gint _tmp21_ = 0;
					if (!_tmp11_) {
						gint _tmp12_ = 0;
						_tmp12_ = i;
						i = _tmp12_ + 1;
					}
					_tmp11_ = FALSE;
					_tmp13_ = i;
					_tmp14_ = ent;
					_tmp14__length1 = ent_length1;
					if (!(_tmp13_ < _tmp14__length1)) {
						break;
					}
					_tmp15_ = sol;
					_tmp15__length1 = sol_length1;
					_tmp16_ = i;
					_tmp17_ = ent;
					_tmp17__length1 = ent_length1;
					_tmp18_ = i;
					_tmp19_ = _tmp17_[_tmp18_];
					_tmp20_ = atoi (_tmp19_);
					_tmp15_[_tmp16_] = _tmp20_;
					_tmp21_ = _tmp15_[_tmp16_];
				}
			}
		}
		ent = (_vala_array_free (ent, ent_length1, (GDestroyNotify) g_free), NULL);
	} else {
		result = 1;
		sol = (g_free (sol), NULL);
		return result;
	}
	_tmp22_ = aumbrales_modelo_db_new ();
	db = _tmp22_;
	_tmp23_ = db;
	_tmp26_ = aumbrales_modelo_db_getConexiones (_tmp23_, &_tmp24_, &_tmp25_);
	h = _tmp26_;
	h_length1 = _tmp24_;
	h_length2 = _tmp25_;
	_tmp27_ = h;
	_tmp27__length1 = h_length1;
	_tmp27__length2 = h_length2;
	_tmp28_ = seed;
	_tmp29_ = aumbrales_aceptacion_solucion_new (_tmp27_, _tmp27__length1, _tmp27__length2, _tmp28_, 2);
	s = _tmp29_;
	_tmp30_ = s;
	_tmp31_ = sol;
	_tmp31__length1 = sol_length1;
	aumbrales_aceptacion_solucion_caminoNoAleatorio (_tmp30_, _tmp31_, _tmp31__length1);
	_tmp32_ = s;
	_tmp33_ = seed;
	_tmp34_ = g_strdup_printf ("%i", _tmp33_);
	_tmp35_ = _tmp34_;
	_tmp36_ = aumbrales_aumbrales_new (_tmp32_, 500, 0.9, 0.0001, 0.0001, _tmp35_);
	_tmp37_ = _tmp36_;
	_g_free0 (_tmp35_);
	a = _tmp37_;
	_tmp38_ = a;
	_tmp39_ = sol;
	_tmp39__length1 = sol_length1;
	aumbrales_aumbrales_aceptacionPorUmbrales (_tmp38_, (gdouble) 4, _tmp39_, _tmp39__length1);
	_tmp40_ = a;
	_tmp41_ = aumbrales_aumbrales_get_mejor (_tmp40_, &_tmp41__length1);
	_tmp42_ = _tmp41_;
	_tmp42__length1 = _tmp41__length1;
	{
		gint* i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp42_;
		i_collection_length1 = _tmp42__length1;
		for (i_it = 0; i_it < _tmp42__length1; i_it = i_it + 1) {
			gint i = 0;
			i = i_collection[i_it];
			{
				FILE* _tmp43_ = NULL;
				gint _tmp44_ = 0;
				_tmp43_ = stdout;
				_tmp44_ = i;
				fprintf (_tmp43_, "%d,", _tmp44_);
			}
		}
	}
	_tmp45_ = stdout;
	fprintf (_tmp45_, "\n");
	_tmp46_ = stdout;
	_tmp47_ = s;
	_tmp48_ = a;
	_tmp49_ = aumbrales_aumbrales_get_mejor (_tmp48_, &_tmp49__length1);
	_tmp50_ = _tmp49_;
	_tmp50__length1 = _tmp49__length1;
	_tmp51_ = aumbrales_aceptacion_solucion_fcosto (_tmp47_, _tmp50_, _tmp50__length1);
	fprintf (_tmp46_, "fcostomejor=%2.9f\n", _tmp51_);
	_tmp52_ = stdout;
	_tmp53_ = s;
	_tmp54_ = a;
	_tmp55_ = aumbrales_aumbrales_get_mejor (_tmp54_, &_tmp55__length1);
	_tmp56_ = _tmp55_;
	_tmp56__length1 = _tmp55__length1;
	_tmp57_ = aumbrales_aceptacion_solucion_factible (_tmp53_, _tmp56_, _tmp56__length1);
	_tmp58_ = bool_to_string (_tmp57_);
	_tmp59_ = _tmp58_;
	fprintf (_tmp52_, "factiblemejor=%s\n", _tmp59_);
	_g_free0 (_tmp59_);
	_tmp60_ = db;
	_tmp62_ = aumbrales_modelo_db_getCiudades (_tmp60_, &_tmp61_);
	l = _tmp62_;
	l_length1 = _tmp61_;
	_l_size_ = l_length1;
	_tmp63_ = l;
	_tmp63__length1 = l_length1;
	_tmp64_ = a;
	_tmp65_ = aumbrales_aumbrales_get_mejor (_tmp64_, &_tmp65__length1);
	_tmp66_ = _tmp65_;
	_tmp66__length1 = _tmp65__length1;
	_tmp67_ = seed;
	aumbrales_main_graficaMapa (_tmp63_, _tmp63__length1, _tmp66_, _tmp66__length1, _tmp67_);
	result = 0;
	l = (_vala_array_free (l, l_length1, (GDestroyNotify) g_object_unref), NULL);
	_g_object_unref0 (a);
	_g_object_unref0 (s);
	h = (g_free (h), NULL);
	_g_object_unref0 (db);
	sol = (g_free (sol), NULL);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return aumbrales_main_main (argv, argc);
}


AumbralesMain* aumbrales_main_construct (GType object_type) {
	AumbralesMain * self = NULL;
	self = (AumbralesMain*) g_object_new (object_type, NULL);
	return self;
}


AumbralesMain* aumbrales_main_new (void) {
	return aumbrales_main_construct (AUMBRALES_TYPE_MAIN);
}


static void aumbrales_main_class_init (AumbralesMainClass * klass) {
	aumbrales_main_parent_class = g_type_class_peek_parent (klass);
}


static void aumbrales_main_instance_init (AumbralesMain * self) {
}


GType aumbrales_main_get_type (void) {
	static volatile gsize aumbrales_main_type_id__volatile = 0;
	if (g_once_init_enter (&aumbrales_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AumbralesMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aumbrales_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AumbralesMain), 0, (GInstanceInitFunc) aumbrales_main_instance_init, NULL };
		GType aumbrales_main_type_id;
		aumbrales_main_type_id = g_type_register_static (G_TYPE_OBJECT, "AumbralesMain", &g_define_type_info, 0);
		g_once_init_leave (&aumbrales_main_type_id__volatile, aumbrales_main_type_id);
	}
	return aumbrales_main_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



