/* AUmbrales.c generated by valac 0.34.7, the Vala compiler
 * generated from AUmbrales.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "aceptacion.h"
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define AUMBRALES_TYPE_AUMBRALES (aumbrales_aumbrales_get_type ())
#define AUMBRALES_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales))
#define AUMBRALES_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))
#define AUMBRALES_IS_AUMBRALES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_IS_AUMBRALES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TYPE_AUMBRALES))
#define AUMBRALES_AUMBRALES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesClass))

typedef struct _AumbralesAumbrales AumbralesAumbrales;
typedef struct _AumbralesAumbralesClass AumbralesAumbralesClass;
typedef struct _AumbralesAumbralesPrivate AumbralesAumbralesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AumbralesAumbrales {
	GObject parent_instance;
	AumbralesAumbralesPrivate * priv;
};

struct _AumbralesAumbralesClass {
	GObjectClass parent_class;
};

struct _AumbralesAumbralesPrivate {
	AumbralesAceptacionSolucion* s;
	gint lote;
	gint* _mejor;
	gint _mejor_length1;
	gint __mejor_size_;
	gint* ultima;
	gint ultima_length1;
	gint _ultima_size_;
	gdouble psi;
	gdouble epsilon;
	gdouble epsilonp;
	gint fac;
	gchar* name;
};


static gpointer aumbrales_aumbrales_parent_class = NULL;

GType aumbrales_aumbrales_get_type (void) G_GNUC_CONST;
#define AUMBRALES_AUMBRALES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), AUMBRALES_TYPE_AUMBRALES, AumbralesAumbralesPrivate))
enum  {
	AUMBRALES_AUMBRALES_DUMMY_PROPERTY
};
AumbralesAumbrales* aumbrales_aumbrales_new (AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name);
AumbralesAumbrales* aumbrales_aumbrales_construct (GType object_type, AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name);
static gdouble aumbrales_aumbrales_calculaLote (AumbralesAumbrales* self, gdouble t);
gint* aumbrales_aumbrales_get_mejor (AumbralesAumbrales* self, int* result_length1);
void aumbrales_aumbrales_set_mejor (AumbralesAumbrales* self, gint* value, int value_length1);
static gint* _vala_array_dup1 (gint* self, int length);
void aumbrales_aumbrales_aceptacionPorUmbrales (AumbralesAumbrales* self, gdouble t, gint* sol, int sol_length1);
static gint* _vala_array_dup2 (gint* self, int length);
static gint* _vala_array_dup3 (gint* self, int length);
static void aumbrales_aumbrales_finalize (GObject* obj);
static void _vala_aumbrales_aumbrales_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_aumbrales_aumbrales_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


AumbralesAumbrales* aumbrales_aumbrales_construct (GType object_type, AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name) {
	AumbralesAumbrales * self = NULL;
	AumbralesAceptacionSolucion* _tmp0_ = NULL;
	AumbralesAceptacionSolucion* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	g_return_val_if_fail (solucion != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	self = (AumbralesAumbrales*) g_object_new (object_type, NULL);
	_tmp0_ = solucion;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->s);
	self->priv->s = _tmp1_;
	_tmp2_ = lote;
	self->priv->lote = _tmp2_;
	_tmp3_ = psi;
	self->priv->psi = _tmp3_;
	_tmp4_ = epsilon;
	self->priv->epsilon = _tmp4_;
	_tmp5_ = epsilonp;
	self->priv->epsilonp = _tmp5_;
	_tmp6_ = name;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp7_;
	return self;
}


AumbralesAumbrales* aumbrales_aumbrales_new (AumbralesAceptacionSolucion* solucion, gint lote, gdouble psi, gdouble epsilon, gdouble epsilonp, const gchar* name) {
	return aumbrales_aumbrales_construct (AUMBRALES_TYPE_AUMBRALES, solucion, lote, psi, epsilon, epsilonp, name);
}


/**
 *Calcula un lote
 */
static gint* _vala_array_dup1 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


static gdouble aumbrales_aumbrales_calculaLote (AumbralesAumbrales* self, gdouble t) {
	gdouble result = 0.0;
	gint c = 0;
	gdouble r = 0.0;
	gdouble _tmp28_ = 0.0;
	gint _tmp29_ = 0;
	g_return_val_if_fail (self != NULL, 0.0);
	c = 0;
	r = (gdouble) 0;
	while (TRUE) {
		gint _tmp0_ = 0;
		gint _tmp1_ = 0;
		gdouble fsl = 0.0;
		AumbralesAceptacionSolucion* _tmp2_ = NULL;
		gint* _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		gdouble _tmp4_ = 0.0;
		gdouble _tmp5_ = 0.0;
		gint* sprima = NULL;
		AumbralesAceptacionSolucion* _tmp6_ = NULL;
		gint* _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		gint _tmp8_ = 0;
		gint* _tmp9_ = NULL;
		gint sprima_length1 = 0;
		gint _sprima_size_ = 0;
		gdouble fsp = 0.0;
		AumbralesAceptacionSolucion* _tmp10_ = NULL;
		gint* _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		gdouble _tmp12_ = 0.0;
		gdouble _tmp13_ = 0.0;
		gdouble _tmp14_ = 0.0;
		_tmp0_ = c;
		_tmp1_ = self->priv->lote;
		if (!(_tmp0_ < _tmp1_)) {
			break;
		}
		_tmp2_ = self->priv->s;
		_tmp3_ = self->priv->ultima;
		_tmp3__length1 = self->priv->ultima_length1;
		_tmp4_ = aumbrales_aceptacion_solucion_fcosto (_tmp2_, _tmp3_, _tmp3__length1);
		_tmp5_ = t;
		fsl = _tmp4_ + _tmp5_;
		_tmp6_ = self->priv->s;
		_tmp7_ = self->priv->ultima;
		_tmp7__length1 = self->priv->ultima_length1;
		_tmp9_ = aumbrales_aceptacion_solucion_vecino (_tmp6_, _tmp7_, _tmp7__length1, &_tmp8_);
		sprima = _tmp9_;
		sprima_length1 = _tmp8_;
		_sprima_size_ = sprima_length1;
		_tmp10_ = self->priv->s;
		_tmp11_ = sprima;
		_tmp11__length1 = sprima_length1;
		_tmp12_ = aumbrales_aceptacion_solucion_fcosto (_tmp10_, _tmp11_, _tmp11__length1);
		fsp = _tmp12_;
		_tmp13_ = fsp;
		_tmp14_ = fsl;
		if (_tmp13_ <= _tmp14_) {
			gdouble fm = 0.0;
			AumbralesAceptacionSolucion* _tmp15_ = NULL;
			gint* _tmp16_ = NULL;
			gint _tmp16__length1 = 0;
			gint* _tmp17_ = NULL;
			gint _tmp17__length1 = 0;
			gdouble _tmp18_ = 0.0;
			gdouble _tmp19_ = 0.0;
			gdouble _tmp20_ = 0.0;
			gdouble _tmp22_ = 0.0;
			gdouble _tmp23_ = 0.0;
			gint* _tmp24_ = NULL;
			gint _tmp24__length1 = 0;
			gint* _tmp25_ = NULL;
			gint _tmp25__length1 = 0;
			gint _tmp26_ = 0;
			gint _tmp27_ = 0;
			_tmp15_ = self->priv->s;
			_tmp16_ = aumbrales_aumbrales_get_mejor (self, &_tmp16__length1);
			_tmp17_ = _tmp16_;
			_tmp17__length1 = _tmp16__length1;
			_tmp18_ = aumbrales_aceptacion_solucion_fcosto (_tmp15_, _tmp17_, _tmp17__length1);
			fm = _tmp18_;
			_tmp19_ = fsp;
			_tmp20_ = fm;
			if (_tmp19_ <= _tmp20_) {
				gint* _tmp21_ = NULL;
				gint _tmp21__length1 = 0;
				_tmp21_ = sprima;
				_tmp21__length1 = sprima_length1;
				aumbrales_aumbrales_set_mejor (self, _tmp21_, _tmp21__length1);
			}
			_tmp22_ = r;
			_tmp23_ = fsp;
			r = _tmp22_ + _tmp23_;
			_tmp24_ = sprima;
			_tmp24__length1 = sprima_length1;
			_tmp25_ = (_tmp24_ != NULL) ? _vala_array_dup1 (_tmp24_, _tmp24__length1) : ((gpointer) _tmp24_);
			_tmp25__length1 = _tmp24__length1;
			self->priv->ultima = (g_free (self->priv->ultima), NULL);
			self->priv->ultima = _tmp25_;
			self->priv->ultima_length1 = _tmp25__length1;
			self->priv->_ultima_size_ = self->priv->ultima_length1;
			_tmp26_ = c;
			c = _tmp26_ + 1;
			_tmp27_ = self->priv->fac;
			self->priv->fac = _tmp27_ + 1;
		}
		sprima = (g_free (sprima), NULL);
	}
	_tmp28_ = r;
	_tmp29_ = self->priv->lote;
	result = _tmp28_ / _tmp29_;
	return result;
}


/**
 *Aceptacion por umbrales
 */
static gint* _vala_array_dup2 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


void aumbrales_aumbrales_aceptacionPorUmbrales (AumbralesAumbrales* self, gdouble t, gint* sol, int sol_length1) {
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gdouble p = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = sol;
	_tmp0__length1 = sol_length1;
	aumbrales_aumbrales_set_mejor (self, _tmp0_, _tmp0__length1);
	_tmp1_ = sol;
	_tmp1__length1 = sol_length1;
	_tmp2_ = (_tmp1_ != NULL) ? _vala_array_dup2 (_tmp1_, _tmp1__length1) : ((gpointer) _tmp1_);
	_tmp2__length1 = _tmp1__length1;
	self->priv->ultima = (g_free (self->priv->ultima), NULL);
	self->priv->ultima = _tmp2_;
	self->priv->ultima_length1 = _tmp2__length1;
	self->priv->_ultima_size_ = self->priv->ultima_length1;
	p = DBL_MAX;
	while (TRUE) {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		gdouble pprima = 0.0;
		gdouble _tmp12_ = 0.0;
		gdouble _tmp13_ = 0.0;
		_tmp3_ = t;
		_tmp4_ = self->priv->epsilon;
		if (!(_tmp3_ > _tmp4_)) {
			break;
		}
		pprima = (gdouble) 0;
		self->priv->fac = 0;
		while (TRUE) {
			gdouble _tmp5_ = 0.0;
			gdouble _tmp6_ = 0.0;
			gdouble _tmp7_ = 0.0;
			gdouble _tmp8_ = 0.0;
			gdouble _tmp9_ = 0.0;
			gdouble _tmp10_ = 0.0;
			gdouble _tmp11_ = 0.0;
			_tmp5_ = p;
			_tmp6_ = pprima;
			_tmp7_ = fabs (_tmp5_ - _tmp6_);
			_tmp8_ = self->priv->epsilonp;
			if (!(_tmp7_ > _tmp8_)) {
				break;
			}
			_tmp9_ = p;
			pprima = _tmp9_;
			_tmp10_ = t;
			_tmp11_ = aumbrales_aumbrales_calculaLote (self, _tmp10_);
			p = _tmp11_;
		}
		_tmp12_ = self->priv->psi;
		_tmp13_ = t;
		t = _tmp12_ * _tmp13_;
	}
}


gint* aumbrales_aumbrales_get_mejor (AumbralesAumbrales* self, int* result_length1) {
	gint* result;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_mejor;
	_tmp0__length1 = self->priv->_mejor_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gint* _vala_array_dup3 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


void aumbrales_aumbrales_set_mejor (AumbralesAumbrales* self, gint* value, int value_length1) {
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup3 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_mejor = (g_free (self->priv->_mejor), NULL);
	self->priv->_mejor = _tmp1_;
	self->priv->_mejor_length1 = _tmp1__length1;
	self->priv->__mejor_size_ = self->priv->_mejor_length1;
}


static void aumbrales_aumbrales_class_init (AumbralesAumbralesClass * klass) {
	aumbrales_aumbrales_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AumbralesAumbralesPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_aumbrales_aumbrales_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_aumbrales_aumbrales_set_property;
	G_OBJECT_CLASS (klass)->finalize = aumbrales_aumbrales_finalize;
}


static void aumbrales_aumbrales_instance_init (AumbralesAumbrales * self) {
	self->priv = AUMBRALES_AUMBRALES_GET_PRIVATE (self);
}


static void aumbrales_aumbrales_finalize (GObject* obj) {
	AumbralesAumbrales * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales);
	_g_object_unref0 (self->priv->s);
	self->priv->_mejor = (g_free (self->priv->_mejor), NULL);
	self->priv->ultima = (g_free (self->priv->ultima), NULL);
	_g_free0 (self->priv->name);
	G_OBJECT_CLASS (aumbrales_aumbrales_parent_class)->finalize (obj);
}


GType aumbrales_aumbrales_get_type (void) {
	static volatile gsize aumbrales_aumbrales_type_id__volatile = 0;
	if (g_once_init_enter (&aumbrales_aumbrales_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AumbralesAumbralesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aumbrales_aumbrales_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AumbralesAumbrales), 0, (GInstanceInitFunc) aumbrales_aumbrales_instance_init, NULL };
		GType aumbrales_aumbrales_type_id;
		aumbrales_aumbrales_type_id = g_type_register_static (G_TYPE_OBJECT, "AumbralesAumbrales", &g_define_type_info, 0);
		g_once_init_leave (&aumbrales_aumbrales_type_id__volatile, aumbrales_aumbrales_type_id);
	}
	return aumbrales_aumbrales_type_id__volatile;
}


static void _vala_aumbrales_aumbrales_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AumbralesAumbrales * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_aumbrales_aumbrales_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AumbralesAumbrales * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AUMBRALES_TYPE_AUMBRALES, AumbralesAumbrales);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



