/* aceptacion.h generated by valac 0.34.7, the Vala compiler, do not modify */


#ifndef __LIB_ACEPTACION_ACEPTACION_H__
#define __LIB_ACEPTACION_ACEPTACION_H__

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>

G_BEGIN_DECLS


#define AUMBRALES_ACEPTACION_TYPE_SOLUCION (aumbrales_aceptacion_solucion_get_type ())
#define AUMBRALES_ACEPTACION_SOLUCION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucion))
#define AUMBRALES_ACEPTACION_SOLUCION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucionClass))
#define AUMBRALES_ACEPTACION_IS_SOLUCION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION))
#define AUMBRALES_ACEPTACION_IS_SOLUCION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_ACEPTACION_TYPE_SOLUCION))
#define AUMBRALES_ACEPTACION_SOLUCION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucionClass))

typedef struct _AumbralesAceptacionSolucion AumbralesAceptacionSolucion;
typedef struct _AumbralesAceptacionSolucionClass AumbralesAceptacionSolucionClass;
typedef struct _AumbralesAceptacionSolucionPrivate AumbralesAceptacionSolucionPrivate;

struct _AumbralesAceptacionSolucion {
	GObject parent_instance;
	AumbralesAceptacionSolucionPrivate * priv;
};

struct _AumbralesAceptacionSolucionClass {
	GObjectClass parent_class;
};


GType aumbrales_aceptacion_solucion_get_type (void) G_GNUC_CONST;
AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_new (gdouble* map, int map_length1, int map_length2, gint semilla, gint c);
AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_construct (GType object_type, gdouble* map, int map_length1, int map_length2, gint semilla, gint c);
gint* aumbrales_aceptacion_solucion_generaCaminoAleatorio (AumbralesAceptacionSolucion* self, gint n, int* result_length1);
void aumbrales_aceptacion_solucion_caminoNoAleatorio (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
void aumbrales_aceptacion_solucion_maxAvg (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
gint* aumbrales_aceptacion_solucion_vecino (AumbralesAceptacionSolucion* self, gint* s, int s_length1, int* result_length1);
gboolean aumbrales_aceptacion_solucion_factible (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
gdouble aumbrales_aceptacion_solucion_fcosto (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
gint aumbrales_aceptacion_solucion_desconexiones (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
void aumbrales_aceptacion_solucion_imprimeSolucion (AumbralesAceptacionSolucion* self, gint* sol, int sol_length1);


G_END_DECLS

#endif
