/* Solucion.c generated by valac 0.34.7, the Vala compiler
 * generated from Solucion.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define AUMBRALES_ACEPTACION_TYPE_SOLUCION (aumbrales_aceptacion_solucion_get_type ())
#define AUMBRALES_ACEPTACION_SOLUCION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucion))
#define AUMBRALES_ACEPTACION_SOLUCION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucionClass))
#define AUMBRALES_ACEPTACION_IS_SOLUCION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION))
#define AUMBRALES_ACEPTACION_IS_SOLUCION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_ACEPTACION_TYPE_SOLUCION))
#define AUMBRALES_ACEPTACION_SOLUCION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucionClass))

typedef struct _AumbralesAceptacionSolucion AumbralesAceptacionSolucion;
typedef struct _AumbralesAceptacionSolucionClass AumbralesAceptacionSolucionClass;
typedef struct _AumbralesAceptacionSolucionPrivate AumbralesAceptacionSolucionPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _AumbralesAceptacionSolucion {
	GObject parent_instance;
	AumbralesAceptacionSolucionPrivate * priv;
};

struct _AumbralesAceptacionSolucionClass {
	GObjectClass parent_class;
};

struct _AumbralesAceptacionSolucionPrivate {
	gdouble max;
	gdouble avg;
	gdouble* map;
	gint map_length1;
	gint map_length2;
	GRand* rand;
	gint c;
};


static gpointer aumbrales_aceptacion_solucion_parent_class = NULL;

GType aumbrales_aceptacion_solucion_get_type (void) G_GNUC_CONST;
#define AUMBRALES_ACEPTACION_SOLUCION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucionPrivate))
enum  {
	AUMBRALES_ACEPTACION_SOLUCION_DUMMY_PROPERTY
};
AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_new (gdouble* map, int map_length1, int map_length2, gint semilla, gint c);
AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_construct (GType object_type, gdouble* map, int map_length1, int map_length2, gint semilla, gint c);
static gdouble* _vala_array_dup1 (gdouble* self, int length);
gint* aumbrales_aceptacion_solucion_generaCaminoAleatorio (AumbralesAceptacionSolucion* self, gint n, int* result_length1);
void aumbrales_aceptacion_solucion_maxAvg (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
void aumbrales_aceptacion_solucion_caminoNoAleatorio (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
gint* aumbrales_aceptacion_solucion_vecino (AumbralesAceptacionSolucion* self, gint* s, int s_length1, int* result_length1);
gboolean aumbrales_aceptacion_solucion_factible (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
gdouble aumbrales_aceptacion_solucion_fcosto (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
static gdouble aumbrales_aceptacion_solucion_dprima (AumbralesAceptacionSolucion* self, gint c1, gint c2);
gint aumbrales_aceptacion_solucion_desconexiones (AumbralesAceptacionSolucion* self, gint* s, int s_length1);
void aumbrales_aceptacion_solucion_imprimeSolucion (AumbralesAceptacionSolucion* self, gint* sol, int sol_length1);
static void aumbrales_aceptacion_solucion_finalize (GObject* obj);


/**
 * Constructor 
 */
static gdouble* _vala_array_dup1 (gdouble* self, int length) {
	return g_memdup (self, length * sizeof (gdouble));
}


AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_construct (GType object_type, gdouble* map, int map_length1, int map_length2, gint semilla, gint c) {
	AumbralesAceptacionSolucion * self = NULL;
	gdouble* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	gdouble* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp1__length2 = 0;
	GRand* _tmp2_ = NULL;
	GRand* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	self = (AumbralesAceptacionSolucion*) g_object_new (object_type, NULL);
	_tmp0_ = map;
	_tmp0__length1 = map_length1;
	_tmp0__length2 = map_length2;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1 * _tmp0__length2) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	_tmp1__length2 = _tmp0__length2;
	self->priv->map = (g_free (self->priv->map), NULL);
	self->priv->map = _tmp1_;
	self->priv->map_length1 = _tmp1__length1;
	self->priv->map_length2 = _tmp1__length2;
	_tmp2_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp2_;
	_tmp3_ = self->priv->rand;
	_tmp4_ = semilla;
	g_rand_set_seed (_tmp3_, (guint32) _tmp4_);
	self->priv->max = (gdouble) 0;
	self->priv->avg = (gdouble) 0;
	_tmp5_ = c;
	self->priv->c = _tmp5_;
	return self;
}


AumbralesAceptacionSolucion* aumbrales_aceptacion_solucion_new (gdouble* map, int map_length1, int map_length2, gint semilla, gint c) {
	return aumbrales_aceptacion_solucion_construct (AUMBRALES_ACEPTACION_TYPE_SOLUCION, map, map_length1, map_length2, semilla, c);
}


/**
 * Genera un camino aleatorio de tamanio n 
 * partir de la grafica y de la semilla 
 */
gint* aumbrales_aceptacion_solucion_generaCaminoAleatorio (AumbralesAceptacionSolucion* self, gint n, int* result_length1) {
	gint* result = NULL;
	gint* camino = NULL;
	gint _tmp0_ = 0;
	gint* _tmp1_ = NULL;
	gint camino_length1 = 0;
	gint _camino_size_ = 0;
	gint x = 0;
	GRand* _tmp2_ = NULL;
	gint32 _tmp3_ = 0;
	gint i = 0;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint* _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	FILE* _tmp23_ = NULL;
	gdouble _tmp24_ = 0.0;
	FILE* _tmp25_ = NULL;
	gdouble _tmp26_ = 0.0;
	gint* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = n;
	_tmp1_ = g_new0 (gint, _tmp0_);
	camino = _tmp1_;
	camino_length1 = _tmp0_;
	_camino_size_ = camino_length1;
	_tmp2_ = self->priv->rand;
	_tmp3_ = g_rand_int_range (_tmp2_, (gint32) 1, (gint32) 278);
	x = (gint) _tmp3_;
	i = 0;
	_tmp4_ = camino;
	_tmp4__length1 = camino_length1;
	_tmp5_ = i;
	_tmp6_ = x;
	_tmp4_[_tmp5_] = _tmp6_;
	_tmp7_ = _tmp4_[_tmp5_];
	while (TRUE) {
		gint _tmp8_ = 0;
		gint y = 0;
		GRand* _tmp9_ = NULL;
		gint32 _tmp10_ = 0;
		gdouble* _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		gint _tmp11__length2 = 0;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		gdouble _tmp14_ = 0.0;
		_tmp8_ = n;
		if (!((_tmp8_ - 1) > 0)) {
			break;
		}
		_tmp9_ = self->priv->rand;
		_tmp10_ = g_rand_int_range (_tmp9_, (gint32) 1, (gint32) 278);
		y = (gint) _tmp10_;
		_tmp11_ = self->priv->map;
		_tmp11__length1 = self->priv->map_length1;
		_tmp11__length2 = self->priv->map_length2;
		_tmp12_ = x;
		_tmp13_ = y;
		_tmp14_ = _tmp11_[(_tmp12_ * _tmp11__length2) + _tmp13_];
		if (_tmp14_ > ((gdouble) 0)) {
			gint _tmp15_ = 0;
			gint* _tmp16_ = NULL;
			gint _tmp16__length1 = 0;
			gint _tmp17_ = 0;
			gint _tmp18_ = 0;
			gint _tmp19_ = 0;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			_tmp15_ = i;
			i = _tmp15_ + 1;
			_tmp16_ = camino;
			_tmp16__length1 = camino_length1;
			_tmp17_ = i;
			_tmp18_ = y;
			_tmp16_[_tmp17_] = _tmp18_;
			_tmp19_ = _tmp16_[_tmp17_];
			_tmp20_ = n;
			n = _tmp20_ - 1;
			_tmp21_ = y;
			x = _tmp21_;
		}
	}
	_tmp22_ = camino;
	_tmp22__length1 = camino_length1;
	aumbrales_aceptacion_solucion_maxAvg (self, _tmp22_, _tmp22__length1);
	_tmp23_ = stderr;
	_tmp24_ = self->priv->max;
	fprintf (_tmp23_, "max=========>%2.9f\n", _tmp24_);
	_tmp25_ = stderr;
	_tmp26_ = self->priv->avg;
	fprintf (_tmp25_, "avg=========>%2.9f\n", _tmp26_);
	_tmp27_ = camino;
	_tmp27__length1 = camino_length1;
	if (result_length1) {
		*result_length1 = _tmp27__length1;
	}
	result = _tmp27_;
	return result;
}


void aumbrales_aceptacion_solucion_caminoNoAleatorio (AumbralesAceptacionSolucion* self, gint* s, int s_length1) {
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = s;
	_tmp0__length1 = s_length1;
	aumbrales_aceptacion_solucion_maxAvg (self, _tmp0_, _tmp0__length1);
}


void aumbrales_aceptacion_solucion_maxAvg (AumbralesAceptacionSolucion* self, gint* s, int s_length1) {
	gint c = 0;
	gdouble d = 0.0;
	gdouble _tmp31_ = 0.0;
	gint _tmp32_ = 0;
	g_return_if_fail (self != NULL);
	c = 0;
	d = (gdouble) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gint* _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = s;
				_tmp3__length1 = s_length1;
				if (!(_tmp2_ < (_tmp3__length1 - 2))) {
					break;
				}
				{
					gint j = 0;
					gint _tmp4_ = 0;
					_tmp4_ = i;
					j = _tmp4_ + 1;
					{
						gboolean _tmp5_ = FALSE;
						_tmp5_ = TRUE;
						while (TRUE) {
							gint _tmp7_ = 0;
							gint* _tmp8_ = NULL;
							gint _tmp8__length1 = 0;
							gdouble* _tmp9_ = NULL;
							gint _tmp9__length1 = 0;
							gint _tmp9__length2 = 0;
							gint* _tmp10_ = NULL;
							gint _tmp10__length1 = 0;
							gint _tmp11_ = 0;
							gint _tmp12_ = 0;
							gint* _tmp13_ = NULL;
							gint _tmp13__length1 = 0;
							gint _tmp14_ = 0;
							gint _tmp15_ = 0;
							gdouble _tmp16_ = 0.0;
							if (!_tmp5_) {
								gint _tmp6_ = 0;
								_tmp6_ = j;
								j = _tmp6_ + 1;
							}
							_tmp5_ = FALSE;
							_tmp7_ = j;
							_tmp8_ = s;
							_tmp8__length1 = s_length1;
							if (!(_tmp7_ < (_tmp8__length1 - 1))) {
								break;
							}
							_tmp9_ = self->priv->map;
							_tmp9__length1 = self->priv->map_length1;
							_tmp9__length2 = self->priv->map_length2;
							_tmp10_ = s;
							_tmp10__length1 = s_length1;
							_tmp11_ = i;
							_tmp12_ = _tmp10_[_tmp11_];
							_tmp13_ = s;
							_tmp13__length1 = s_length1;
							_tmp14_ = j;
							_tmp15_ = _tmp13_[_tmp14_];
							_tmp16_ = _tmp9_[(_tmp12_ * _tmp9__length2) + _tmp15_];
							if (_tmp16_ > ((gdouble) 0)) {
								gdouble de = 0.0;
								gdouble* _tmp17_ = NULL;
								gint _tmp17__length1 = 0;
								gint _tmp17__length2 = 0;
								gint* _tmp18_ = NULL;
								gint _tmp18__length1 = 0;
								gint _tmp19_ = 0;
								gint _tmp20_ = 0;
								gint* _tmp21_ = NULL;
								gint _tmp21__length1 = 0;
								gint _tmp22_ = 0;
								gint _tmp23_ = 0;
								gdouble _tmp24_ = 0.0;
								gdouble _tmp25_ = 0.0;
								gdouble _tmp26_ = 0.0;
								gdouble _tmp27_ = 0.0;
								gdouble _tmp28_ = 0.0;
								gdouble _tmp29_ = 0.0;
								gint _tmp30_ = 0;
								_tmp17_ = self->priv->map;
								_tmp17__length1 = self->priv->map_length1;
								_tmp17__length2 = self->priv->map_length2;
								_tmp18_ = s;
								_tmp18__length1 = s_length1;
								_tmp19_ = i;
								_tmp20_ = _tmp18_[_tmp19_];
								_tmp21_ = s;
								_tmp21__length1 = s_length1;
								_tmp22_ = j;
								_tmp23_ = _tmp21_[_tmp22_];
								_tmp24_ = _tmp17_[(_tmp20_ * _tmp17__length2) + _tmp23_];
								de = _tmp24_;
								_tmp25_ = self->priv->max;
								_tmp26_ = de;
								_tmp27_ = MAX (_tmp25_, _tmp26_);
								self->priv->max = _tmp27_;
								_tmp28_ = d;
								_tmp29_ = de;
								d = _tmp28_ + _tmp29_;
								_tmp30_ = c;
								c = _tmp30_ + 1;
							}
						}
					}
				}
			}
		}
	}
	_tmp31_ = d;
	_tmp32_ = c;
	self->priv->avg = _tmp31_ / _tmp32_;
}


/**
 * Genera un vecino apartir de una solucion
 */
gint* aumbrales_aceptacion_solucion_vecino (AumbralesAceptacionSolucion* self, gint* s, int s_length1, int* result_length1) {
	gint* result = NULL;
	gint l = 0;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint c1 = 0;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint32 _tmp3_ = 0;
	gint c2 = 0;
	GRand* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint32 _tmp6_ = 0;
	gint* v = NULL;
	gint _tmp7_ = 0;
	gint* _tmp8_ = NULL;
	gint v_length1 = 0;
	gint _v_size_ = 0;
	gint* _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	gint _tmp20_ = 0;
	gint* _tmp21_ = NULL;
	gint _tmp21__length1 = 0;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint* _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	gint _tmp26_ = 0;
	gint* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	gint _tmp30_ = 0;
	gint* _tmp31_ = NULL;
	gint _tmp31__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = s;
	_tmp0__length1 = s_length1;
	l = _tmp0__length1;
	_tmp1_ = self->priv->rand;
	_tmp2_ = l;
	_tmp3_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) _tmp2_);
	c1 = (gint) _tmp3_;
	_tmp4_ = self->priv->rand;
	_tmp5_ = l;
	_tmp6_ = g_rand_int_range (_tmp4_, (gint32) 0, (gint32) _tmp5_);
	c2 = (gint) _tmp6_;
	_tmp7_ = l;
	_tmp8_ = g_new0 (gint, _tmp7_);
	v = _tmp8_;
	v_length1 = _tmp7_;
	_v_size_ = v_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp9_ = FALSE;
			_tmp9_ = TRUE;
			while (TRUE) {
				gint _tmp11_ = 0;
				gint _tmp12_ = 0;
				gint* _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				gint _tmp14_ = 0;
				gint* _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint _tmp16_ = 0;
				gint _tmp17_ = 0;
				gint _tmp18_ = 0;
				if (!_tmp9_) {
					gint _tmp10_ = 0;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp11_ = i;
				_tmp12_ = l;
				if (!(_tmp11_ < _tmp12_)) {
					break;
				}
				_tmp13_ = v;
				_tmp13__length1 = v_length1;
				_tmp14_ = i;
				_tmp15_ = s;
				_tmp15__length1 = s_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_];
				_tmp13_[_tmp14_] = _tmp17_;
				_tmp18_ = _tmp13_[_tmp14_];
			}
		}
	}
	_tmp19_ = v;
	_tmp19__length1 = v_length1;
	_tmp20_ = c1;
	_tmp21_ = s;
	_tmp21__length1 = s_length1;
	_tmp22_ = c2;
	_tmp23_ = _tmp21_[_tmp22_];
	_tmp19_[_tmp20_] = _tmp23_;
	_tmp24_ = _tmp19_[_tmp20_];
	_tmp25_ = v;
	_tmp25__length1 = v_length1;
	_tmp26_ = c2;
	_tmp27_ = s;
	_tmp27__length1 = s_length1;
	_tmp28_ = c1;
	_tmp29_ = _tmp27_[_tmp28_];
	_tmp25_[_tmp26_] = _tmp29_;
	_tmp30_ = _tmp25_[_tmp26_];
	_tmp31_ = v;
	_tmp31__length1 = v_length1;
	if (result_length1) {
		*result_length1 = _tmp31__length1;
	}
	result = _tmp31_;
	return result;
}


/**
 * Verifica si una solucion es factible 
 */
gboolean aumbrales_aceptacion_solucion_factible (AumbralesAceptacionSolucion* self, gint* s, int s_length1) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gint* _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				gdouble* _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp4__length2 = 0;
				gint* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				gint* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gdouble _tmp11_ = 0.0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = s;
				_tmp3__length1 = s_length1;
				if (!(_tmp2_ < (_tmp3__length1 - 1))) {
					break;
				}
				_tmp4_ = self->priv->map;
				_tmp4__length1 = self->priv->map_length1;
				_tmp4__length2 = self->priv->map_length2;
				_tmp5_ = s;
				_tmp5__length1 = s_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = s;
				_tmp8__length1 = s_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_ + 1];
				_tmp11_ = _tmp4_[(_tmp7_ * _tmp4__length2) + _tmp10_];
				if (_tmp11_ <= ((gdouble) 0)) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}


/**
 * Funcion de costo
**/
gdouble aumbrales_aceptacion_solucion_fcosto (AumbralesAceptacionSolucion* self, gint* s, int s_length1) {
	gdouble result = 0.0;
	gdouble sum = 0.0;
	gdouble avgf = 0.0;
	gdouble _tmp12_ = 0.0;
	gint* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	gdouble _tmp14_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	sum = (gdouble) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gint* _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				gdouble _tmp4_ = 0.0;
				gint* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				gint* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gdouble _tmp11_ = 0.0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = s;
				_tmp3__length1 = s_length1;
				if (!(_tmp2_ < (_tmp3__length1 - 1))) {
					break;
				}
				_tmp4_ = sum;
				_tmp5_ = s;
				_tmp5__length1 = s_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = s;
				_tmp8__length1 = s_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_ + 1];
				_tmp11_ = aumbrales_aceptacion_solucion_dprima (self, _tmp7_, _tmp10_);
				sum = _tmp4_ + _tmp11_;
			}
		}
	}
	_tmp12_ = self->priv->avg;
	_tmp13_ = s;
	_tmp13__length1 = s_length1;
	avgf = (_tmp12_ * _tmp13__length1) - 1;
	_tmp14_ = sum;
	result = _tmp14_ / avgf;
	return result;
}


static gdouble aumbrales_aceptacion_solucion_dprima (AumbralesAceptacionSolucion* self, gint c1, gint c2) {
	gdouble result = 0.0;
	gdouble distancia = 0.0;
	gdouble* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gdouble _tmp3_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	distancia = (gdouble) 0;
	_tmp0_ = self->priv->map;
	_tmp0__length1 = self->priv->map_length1;
	_tmp0__length2 = self->priv->map_length2;
	_tmp1_ = c1;
	_tmp2_ = c2;
	_tmp3_ = _tmp0_[(_tmp1_ * _tmp0__length2) + _tmp2_];
	if (_tmp3_ <= ((gdouble) 0)) {
		gdouble _tmp4_ = 0.0;
		gint _tmp5_ = 0;
		_tmp4_ = self->priv->max;
		_tmp5_ = self->priv->c;
		distancia = _tmp4_ * _tmp5_;
	} else {
		gdouble* _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		gint _tmp6__length2 = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gdouble _tmp9_ = 0.0;
		_tmp6_ = self->priv->map;
		_tmp6__length1 = self->priv->map_length1;
		_tmp6__length2 = self->priv->map_length2;
		_tmp7_ = c1;
		_tmp8_ = c2;
		_tmp9_ = _tmp6_[(_tmp7_ * _tmp6__length2) + _tmp8_];
		distancia = _tmp9_;
	}
	result = distancia;
	return result;
}


gint aumbrales_aceptacion_solucion_desconexiones (AumbralesAceptacionSolucion* self, gint* s, int s_length1) {
	gint result = 0;
	gint c = 0;
	g_return_val_if_fail (self != NULL, 0);
	c = 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gint* _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				gdouble* _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp4__length2 = 0;
				gint* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				gint* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gdouble _tmp11_ = 0.0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = s;
				_tmp3__length1 = s_length1;
				if (!(_tmp2_ < (_tmp3__length1 - 1))) {
					break;
				}
				_tmp4_ = self->priv->map;
				_tmp4__length1 = self->priv->map_length1;
				_tmp4__length2 = self->priv->map_length2;
				_tmp5_ = s;
				_tmp5__length1 = s_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = s;
				_tmp8__length1 = s_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_ + 1];
				_tmp11_ = _tmp4_[(_tmp7_ * _tmp4__length2) + _tmp10_];
				if (_tmp11_ < ((gdouble) 0)) {
					gint _tmp12_ = 0;
					_tmp12_ = c;
					c = _tmp12_ + 1;
				}
			}
		}
	}
	result = c;
	return result;
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


void aumbrales_aceptacion_solucion_imprimeSolucion (AumbralesAceptacionSolucion* self, gint* sol, int sol_length1) {
	gchar* s = NULL;
	gchar* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	s = _tmp0_;
	_tmp1_ = sol;
	_tmp1__length1 = sol_length1;
	{
		gint* i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp1_;
		i_collection_length1 = _tmp1__length1;
		for (i_it = 0; i_it < _tmp1__length1; i_it = i_it + 1) {
			gint i = 0;
			i = i_collection[i_it];
			{
				const gchar* _tmp2_ = NULL;
				gint _tmp3_ = 0;
				gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				gchar* _tmp8_ = NULL;
				_tmp2_ = s;
				_tmp3_ = i;
				_tmp4_ = g_strdup_printf ("%i", _tmp3_);
				_tmp5_ = _tmp4_;
				_tmp6_ = g_strconcat (_tmp5_, ",", NULL);
				_tmp7_ = _tmp6_;
				_tmp8_ = g_strconcat (_tmp2_, _tmp7_, NULL);
				_g_free0 (s);
				s = _tmp8_;
				_g_free0 (_tmp7_);
				_g_free0 (_tmp5_);
			}
		}
	}
	{
		gchar* name = NULL;
		gint* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gdouble _tmp10_ = 0.0;
		gchar* _tmp11_ = NULL;
		GFile* file = NULL;
		const gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		GFile* _tmp17_ = NULL;
		GFile* _tmp18_ = NULL;
		GFile* _tmp19_ = NULL;
		gboolean _tmp20_ = FALSE;
		GFileOutputStream* _tmp22_ = NULL;
		GFile* _tmp23_ = NULL;
		GFileOutputStream* _tmp24_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp25_ = NULL;
		GDataOutputStream* _tmp26_ = NULL;
		const gchar* _tmp27_ = NULL;
		_tmp9_ = sol;
		_tmp9__length1 = sol_length1;
		_tmp10_ = aumbrales_aceptacion_solucion_fcosto (self, _tmp9_, _tmp9__length1);
		_tmp11_ = double_to_string (_tmp10_);
		name = _tmp11_;
		_tmp12_ = name;
		_tmp13_ = g_strconcat ("experimentos/", _tmp12_, NULL);
		_tmp14_ = _tmp13_;
		_tmp15_ = g_strconcat (_tmp14_, ".tsp", NULL);
		_tmp16_ = _tmp15_;
		_tmp17_ = g_file_new_for_path (_tmp16_);
		_tmp18_ = _tmp17_;
		_g_free0 (_tmp16_);
		_g_free0 (_tmp14_);
		file = _tmp18_;
		_tmp19_ = file;
		_tmp20_ = g_file_query_exists (_tmp19_, NULL);
		if (_tmp20_) {
			GFile* _tmp21_ = NULL;
			_tmp21_ = file;
			g_file_delete (_tmp21_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (file);
				_g_free0 (name);
				goto __catch0_g_error;
			}
		}
		_tmp23_ = file;
		_tmp24_ = g_file_create (_tmp23_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
		_tmp22_ = _tmp24_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (file);
			_g_free0 (name);
			goto __catch0_g_error;
		}
		_tmp25_ = g_data_output_stream_new ((GOutputStream*) _tmp22_);
		dos = _tmp25_;
		_tmp26_ = dos;
		_tmp27_ = s;
		g_data_output_stream_put_string (_tmp26_, _tmp27_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp22_);
			_g_object_unref0 (file);
			_g_free0 (name);
			goto __catch0_g_error;
		}
		_g_object_unref0 (dos);
		_g_object_unref0 (_tmp22_);
		_g_object_unref0 (file);
		_g_free0 (name);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp28_ = NULL;
		GError* _tmp29_ = NULL;
		const gchar* _tmp30_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp28_ = stderr;
		_tmp29_ = e;
		_tmp30_ = _tmp29_->message;
		fprintf (_tmp28_, "%s\n", _tmp30_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (s);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (s);
}


static void aumbrales_aceptacion_solucion_class_init (AumbralesAceptacionSolucionClass * klass) {
	aumbrales_aceptacion_solucion_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AumbralesAceptacionSolucionPrivate));
	G_OBJECT_CLASS (klass)->finalize = aumbrales_aceptacion_solucion_finalize;
}


static void aumbrales_aceptacion_solucion_instance_init (AumbralesAceptacionSolucion * self) {
	self->priv = AUMBRALES_ACEPTACION_SOLUCION_GET_PRIVATE (self);
}


static void aumbrales_aceptacion_solucion_finalize (GObject* obj) {
	AumbralesAceptacionSolucion * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AUMBRALES_ACEPTACION_TYPE_SOLUCION, AumbralesAceptacionSolucion);
	self->priv->map = (g_free (self->priv->map), NULL);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (aumbrales_aceptacion_solucion_parent_class)->finalize (obj);
}


GType aumbrales_aceptacion_solucion_get_type (void) {
	static volatile gsize aumbrales_aceptacion_solucion_type_id__volatile = 0;
	if (g_once_init_enter (&aumbrales_aceptacion_solucion_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AumbralesAceptacionSolucionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aumbrales_aceptacion_solucion_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AumbralesAceptacionSolucion), 0, (GInstanceInitFunc) aumbrales_aceptacion_solucion_instance_init, NULL };
		GType aumbrales_aceptacion_solucion_type_id;
		aumbrales_aceptacion_solucion_type_id = g_type_register_static (G_TYPE_OBJECT, "AumbralesAceptacionSolucion", &g_define_type_info, 0);
		g_once_init_leave (&aumbrales_aceptacion_solucion_type_id__volatile, aumbrales_aceptacion_solucion_type_id);
	}
	return aumbrales_aceptacion_solucion_type_id__volatile;
}



